### ISSUE TITLE
on "marketmaker XBTUSD" 'module' object has no attribute 'reload'

### ISSUE THREAD

**Issue by gasperko** [BitMEX/sample-market-maker#103]
I followed instructions in README file, but when I try to run it(on testnet) it gives me this error:
```
 #: ./marketmaker XBTUSD
Traceback (most recent call last):
  File "./marketmaker", line 3, in <module>
    from market_maker import market_maker
  File "/root/bitmex_bot/market_maker/market_maker.py", line 11, in <module>
    from market_maker import bitmex
  File "/root/bitmex_bot/market_maker/bitmex.py", line 12, in <module>
    from market_maker.ws.ws_thread import BitMEXWebsocket
  File "/root/bitmex_bot/market_maker/ws/ws_thread.py", line 10, in <module>
    from market_maker.settings import settings
  File "/root/bitmex_bot/market_maker/settings.py", line 25, in <module>
    userSettings = import_path(os.path.join('.', 'settings'))
  File "/root/bitmex_bot/market_maker/settings.py", line 20, in import_path
    importlib.reload(module)  # Might be out of date
AttributeError: 'module' object has no attribute 'reload'
```

Any help would be appreciated

**Comment by AlexADittrich** [comment]
How did you install?

**Comment by gasperko** [comment]
`pip install bitmex-market-maker` and then `marketmaker setup`

**Comment by gasperko** [comment]
I find the problem and the solution.
The problem is in instructions...
It's not `pip install bitmex-market-maker` because that would mean it uses Python2.7 but in our case we need Python3.
So the correct command for installing is `pip3 install bitmex-market-maker` now it's working without a problem
