### ISSUE TITLE
Error in atexit._run_exitfuncs:

### ISSUE THREAD

**Issue by ak9250** [BitMEX/sample-market-maker#112]
2018-05-11 22:56:40,434 - INFO - market_maker - Shutting down. All open orders will be cancelled.
2018-05-11 22:56:40,435 - INFO - market_maker - Resetting current position. Canceling all existing orders.
2018-05-11 22:56:40,435 - INFO - bitmex - sending req to https://www.bitmex.com/api/v1/order: {"filter": "{\"ordStatus.isTerminated\": false, \"symbol\": \"XBTUSD\"}", "count": 500}
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/market_maker/market_maker.py", line 497, in exit
    sys.exit()
SystemExit

**Comment by ak9250** [comment]
got it again while running live 

2018-05-15 14:20:44,760 - INFO - bitmex - sending req to https://www.bitmex.com/api/v1/order: {"orderID": ["b753182d-5272-5a16-9e3c-5ae4c6448555", "eb93b305-b399-251e-9022-64303757052a", "10bde54d-db75-deda-5dea-fed06ecba413", "ab62b46e-2dab-08c0-29e7-ba81d3a19d41", "dea2b8d7-8dd2-e412-cb86-347944dbfc00", "8ad7ea1f-5254-9ecf-d300-ce19190b9cea", "360c85f8-17d6-68d7-8a34-d865ed611bbf", "1fd913ff-5a85-db67-c283-b658405d3cfd", "8f75bba9-9fd9-fee6-f99b-ecfd950f1968", "d208a56e-d64c-2b4b-4c89-0d43dac4bcfa", "33cacae4-7d56-8c90-996c-7b8a91ddfd4d", "ef51b4a9-1724-b9f4-b1a7-9bcf39d79fe0"]}
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/market_maker/market_maker.py", line 497, in exit
    sys.exit()
SystemExit

**Comment by ryanfox** [comment]
That is the market maker's normal shutdown procedure when it encounters an error. Is there any other error message?
