### ISSUE TITLE
run marketmaker ,get error message

### ISSUE THREAD

**Issue by zhangarejiu** [BitMEX/sample-market-maker#123]
2018-06-11 12:36:47,474 - INFO - market_maker - BitMEX Market Maker Version: v1.4

2018-06-11 12:36:47,479 - INFO - ws_thread - Connecting to wss://testnet.bitmex.com/realtime?subscribe=quote:XBTUSD,trade:XBTUSD,instrument,order:XBTUSD,execution:XBTUSD,margin,position
2018-06-11 12:36:47,481 - INFO - ws_thread - Authenticating with API Key.
2018-06-11 12:36:47,489 - INFO - ws_thread - Started thread
2018-06-11 12:36:49,490 - INFO - ws_thread - Connected to WS. Waiting for data images, this may take a moment...
2018-06-11 12:36:50,899 - INFO - ws_thread - Got all market data. Starting.
2018-06-11 12:36:50,900 - INFO - market_maker - Using symbol XBTUSD.
2018-06-11 12:36:50,902 - INFO - market_maker - Order Manager initializing, connecting to BitMEX. Live run: executing real trades.
2018-06-11 12:36:50,903 - INFO - market_maker - Resetting current position. Canceling all existing orders.
2018-06-11 12:36:50,907 - INFO - bitmex - sending req to https://testnet.bitmex.com/api/v1/order: {"filter": "{\"symbol\": \"XBTUSD\", \"ordStatus.isTerminated\": false}", "count": 500}
Traceback (most recent call last):
  File "/home/jiu/mywork/py3env/lib/python3.5/site-packages/market_maker/bitmex.py", line 263, in _curl_bitmex
    response.raise_for_status()
  File "/home/jiu/mywork/py3env/lib/python3.5/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://testnet.bitmex.com/api/v1/order?filter=%7B%22symbol%22%3A+%22XBTUSD%22%2C+%22ordStatus.isTerminated%22%3A+false%7D&count=500

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jiu/mywork/py3env/bin/marketmaker", line 11, in <module>
    sys.exit(run())
  File "/home/jiu/mywork/py3env/lib/python3.5/site-packages/market_maker/__init__.py", line 22, in run
    market_maker.run()
  File "/home/jiu/mywork/py3env/lib/python3.5/site-packages/market_maker/market_maker.py", line 543, in run
    om = OrderManager()
  File "/home/jiu/mywork/py3env/lib/python3.5/site-packages/market_maker/market_maker.py", line 220, in __init__
    self.reset()
  File "/home/jiu/mywork/py3env/lib/python3.5/site-packages/market_maker/market_maker.py", line 223, in reset
    self.exchange.cancel_all_orders()
  File "/home/jiu/mywork/py3env/lib/python3.5/site-packages/market_maker/market_maker.py", line 60, in cancel_all_orders
    orders = self.bitmex.http_open_orders()
  File "/home/jiu/mywork/py3env/lib/python3.5/site-packages/market_maker/bitmex.py", line 104, in wrapped
    return fn(self, *args, **kwargs)
  File "/home/jiu/mywork/py3env/lib/python3.5/site-packages/market_maker/bitmex.py", line 195, in http_open_orders
    verb="GET"
  File "/home/jiu/mywork/py3env/lib/python3.5/site-packages/market_maker/bitmex.py", line 342, in _curl_bitmex
    return retry()
  File "/home/jiu/mywork/py3env/lib/python3.5/site-packages/market_maker/bitmex.py", line 252, in retry
    raise Exception("Max retries on %s (%s) hit, raising." % (path, json.dumps(postdict or '')))
Exception: Max retries on order ("") hit, raising.
2018-06-11 12:36:53,376 - INFO - market_maker - Shutting down. All open orders will be cancelled.
2018-06-11 12:36:53,381 - INFO - market_maker - Resetting current position. Canceling all existing orders.
2018-06-11 12:36:53,383 - INFO - bitmex - sending req to https://testnet.bitmex.com/api/v1/order: {"filter": "{\"symbol\": \"XBTUSD\", \"ordStatus.isTerminated\": false}", "count": 500}
2018-06-11 12:36:55,503 - INFO - ws_thread - Websocket Closed
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/jiu/mywork/py3env/lib/python3.5/site-packages/market_maker/market_maker.py", line 497, in exit
    sys.exit()
SystemExit

**Comment by Cryptologist1** [comment]
Same issue here, you mange to figure this out?

**Comment by yupengzhi** [comment]
Same issue here, you mange to figure this out?

**Comment by yupengzhi** [comment]
how did you fix it?

**Comment by Cryptologist1** [comment]
You happen to find a solution yupeng?
