### ISSUE TITLE
Connection issue, any suggestions?

### ISSUE THREAD

**Issue by Cryptologist1** [BitMEX/sample-market-maker#124]
Can't get live trading due to this. Any help is appreciated

2018-06-16 00:02:00,075 - INFO - market_maker - BitMEX Market Maker Version: v1.4

2018-06-16 00:02:00,077 - INFO - ws_thread - Connecting to wss://testnet.bitmex.com/realtime?subscribe=quote:XBTUSD,trade:XBTUSD,instrument,order:XBTUSD,execution:XBTUSD,margin,position
2018-06-16 00:02:00,078 - INFO - ws_thread - Authenticating with API Key.
2018-06-16 00:02:00,078 - INFO - ws_thread - Started thread
2018-06-16 00:02:02,079 - INFO - ws_thread - Connected to WS. Waiting for data images, this may take a moment...
2018-06-16 00:02:02,682 - INFO - ws_thread - Got all market data. Starting.
2018-06-16 00:02:02,682 - INFO - market_maker - Using symbol XBTUSD.
2018-06-16 00:02:02,683 - INFO - market_maker - Order Manager initializing, connecting to BitMEX. Live run: executing real trades.
2018-06-16 00:02:02,686 - INFO - market_maker - Resetting current position. Canceling all existing orders.
2018-06-16 00:02:02,686 - INFO - bitmex - sending req to wss://testnet.bitmex.com/realtime/order: {"filter": "{\"ordStatus.isTerminated\": false, \"symbol\": \"XBTUSD\"}", "count": 500}
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python36_64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Rohan\source\repos\virtualenv\Scripts\marketmaker.exe\__main__.py", line 9, in <module>
  File "c:\users\rohan\source\repos\virtualenv\market_maker\__init__.py", line 22, in run
    market_maker.run()
  File "c:\users\rohan\source\repos\virtualenv\market_maker\market_maker.py", line 544, in run
    om = OrderManager()
  File "c:\users\rohan\source\repos\virtualenv\market_maker\market_maker.py", line 220, in __init__
    self.reset()
  File "c:\users\rohan\source\repos\virtualenv\market_maker\market_maker.py", line 223, in reset
    self.exchange.cancel_all_orders()
  File "c:\users\rohan\source\repos\virtualenv\market_maker\market_maker.py", line 60, in cancel_all_orders
    orders = self.bitmex.http_open_orders()
  File "c:\users\rohan\source\repos\virtualenv\market_maker\bitmex.py", line 104, in wrapped
    return fn(self, *args, **kwargs)
  File "c:\users\rohan\source\repos\virtualenv\market_maker\bitmex.py", line 195, in http_open_orders
    verb="GET"
  File "c:\users\rohan\source\repos\virtualenv\market_maker\bitmex.py", line 261, in _curl_bitmex
    response = self.session.send(prepped, timeout=timeout)
  File "c:\users\rohan\source\repos\virtualenv\lib\site-packages\requests\sessions.py", line 616, in send
    adapter = self.get_adapter(url=request.url)
  File "c:\users\rohan\source\repos\virtualenv\lib\site-packages\requests\sessions.py", line 707, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No connection adapters were found for 'wss://testnet.bitmex.com/realtime/order'
2018-06-16 00:02:02,760 - INFO - market_maker - Shutting down. All open orders will be cancelled.
2018-06-16 00:02:02,760 - INFO - market_maker - Resetting current position. Canceling all existing orders.
2018-06-16 00:02:02,760 - INFO - bitmex - sending req to wss://testnet.bitmex.com/realtime/order: {"filter": "{\"ordStatus.isTerminated\": false, \"symbol\": \"XBTUSD\"}", "count": 500}
2018-06-16 00:02:02,761 - INFO - market_maker - Unable to cancel orders: No connection adapters were found for 'wss://testnet.bitmex.com/realtime/order'
2018-06-16 00:02:02,992 - ERROR - _logging - close status: 31522

**Comment by redanthrax** [comment]
Did you solve this? I think you need to create an API key with jist orser. Not have cancel on it.

**Comment by Cryptologist1** [comment]
Hey yup, had the wrong base URL in settings, dumb mistake on my part haha

Thanks

**Comment by froidly** [comment]
i think i have the same error:
requests.exceptions.InvalidSchema: No connection adapters were found for 'wss://testnet.bitmex.com/realtime/order/bulk'

how is the right declaration for an ordner in the testnet envirement?

**Comment by froidly** [comment]
changed the ip to BASE_URL = "https://testnet.bitmex.com/api/v1/"
now i get the error: Unhandled Error: 400 Client Error: Bad Request for url: https://testnet.bitmex.com/api/v1/order/bulk: {"error":{"message":"Limit bulk order is self-crossed","name":"HTTPError"}}

**Comment by froidly** [comment]
i had wrong princes in my order...
