### ISSUE TITLE
400 Client Error: Bad Request

### ISSUE THREAD

**Issue by yupengzhi** [BitMEX/sample-market-maker#126]
2018-06-21 10:59:51,983 - INFO - market_maker - BitMEX Market Maker Version: v1.4

2018-06-21 10:59:51,985 - INFO - ws_thread - Connecting to wss://testnet.bitmex.com/realtime?subscribe=quote:XBTUSD,trade:XBTUSD,instrument,order:XBTUSD,execution:XBTUSD,margin,position
2018-06-21 10:59:51,985 - INFO - ws_thread - Authenticating with API Key.
2018-06-21 10:59:51,986 - INFO - ws_thread - Started thread
2018-06-21 10:59:53,989 - INFO - ws_thread - Connected to WS. Waiting for data images, this may take a moment...
2018-06-21 10:59:54,298 - INFO - ws_thread - Got all market data. Starting.
2018-06-21 10:59:54,299 - INFO - market_maker - Using symbol XBTUSD.
2018-06-21 10:59:54,299 - INFO - market_maker - Order Manager initializing, connecting to BitMEX. Live run: executing real trades.
2018-06-21 10:59:54,299 - INFO - market_maker - Resetting current position. Canceling all existing orders.
2018-06-21 10:59:54,300 - INFO - bitmex - sending req to https://testnet.bitmex.com/api/v1/order: {"count": 500, "filter": "{\"symbol\": \"XBTUSD\", \"ordStatus.isTerminated\": false}"}
2018-06-21 10:59:56,488 - INFO - market_maker - XBTUSD Ticker: Buy: 6760.5, Sell: 6761.0
2018-06-21 10:59:56,489 - INFO - market_maker - Start Positions: Buy: 6727.2, Sell: 6794.3, Mid: 6761.0
2018-06-21 10:59:56,490 - INFO - market_maker - Current XBT Balance: 3.407261
2018-06-21 10:59:56,490 - INFO - market_maker - Current Contract Position: 0
2018-06-21 10:59:56,491 - INFO - market_maker - Contracts Traded This Run: 0
2018-06-21 10:59:56,491 - INFO - market_maker - Total Contract Delta: 0.0000 XBT
2018-06-21 10:59:56,493 - INFO - market_maker - Creating 12 orders:
2018-06-21 10:59:56,494 - INFO - market_maker - Sell 100 @ 6794.5
2018-06-21 10:59:56,494 - INFO - market_maker - Sell 200 @ 6828.5
2018-06-21 10:59:56,495 - INFO - market_maker - Sell 300 @ 6862.5
2018-06-21 10:59:56,495 - INFO - market_maker - Sell 400 @ 6896.5
2018-06-21 10:59:56,496 - INFO - market_maker - Sell 500 @ 6931.0
2018-06-21 10:59:56,497 - INFO - market_maker - Sell 600 @ 6966.0
2018-06-21 10:59:56,497 - INFO - market_maker -  Buy 100 @ 6727.0
2018-06-21 10:59:56,498 - INFO - market_maker -  Buy 200 @ 6693.5
2018-06-21 10:59:56,498 - INFO - market_maker -  Buy 300 @ 6660.5
2018-06-21 10:59:56,499 - INFO - market_maker -  Buy 400 @ 6627.5
2018-06-21 10:59:56,506 - INFO - market_maker -  Buy 500 @ 6594.5
2018-06-21 10:59:56,506 - INFO - market_maker -  Buy 600 @ 6561.5
2018-06-21 10:59:56,509 - INFO - bitmex - sending req to https://testnet.bitmex.com/api/v1/order/bulk: {"orders": [{"symbol": "XBTUSD", "side": "Buy", "clOrdID": "mm_bitmex_VyNRaKV8Sz6w3Xohl7a7OQ", "price": 6561.5, "orderQty": 600}, {"symbol": "XBTUSD", "side": "Buy", "clOrdID": "mm_bitmex_8/TfEt7DRbi3FoOtJdBUBg", "price": 6594.5, "orderQty": 500}, {"symbol": "XBTUSD", "side": "Buy", "clOrdID": "mm_bitmex_2a+UkxN0TWOffHFO+Eznxg", "price": 6627.5, "orderQty": 400}, {"symbol": "XBTUSD", "side": "Buy", "clOrdID": "mm_bitmex_hBE/VSW4Rh2W8b0aMtZebg", "price": 6660.5, "orderQty": 300}, {"symbol": "XBTUSD", "side": "Buy", "clOrdID": "mm_bitmex_tFkC+nhLSA2/sV7TdjhUSg", "price": 6693.5, "orderQty": 200}, {"symbol": "XBTUSD", "side": "Buy", "clOrdID": "mm_bitmex_cs66szgqTyyESw3xkyCmAA", "price": 6727.0, "orderQty": 100}, {"symbol": "XBTUSD", "side": "Sell", "clOrdID": "mm_bitmex_AyHuL7DWSKGaAxgNdan8mQ", "price": 6966.0, "orderQty": 600}, {"symbol": "XBTUSD", "side": "Sell", "clOrdID": "mm_bitmex_IMbbVVIFRqmLQPU2L/uFPA", "price": 6931.0, "orderQty": 500}, {"symbol": "XBTUSD", "side": "Sell", "clOrdID": "mm_bitmex_TNXmjWg6TG+aS/qY3H8fhg", "price": 6896.5, "orderQty": 400}, {"symbol": "XBTUSD", "side": "Sell", "clOrdID": "mm_bitmex_Sxm9rbHsT3iCBudcZWp5rA", "price": 6862.5, "orderQty": 300}, {"symbol": "XBTUSD", "side": "Sell", "clOrdID": "mm_bitmex_HIA5dJu5S+KC6VFOYEkbXA", "price": 6828.5, "orderQty": 200}, {"symbol": "XBTUSD", "side": "Sell", "clOrdID": "mm_bitmex_SP8kQRcQSe2P6VANH29n2w", "price": 6794.5, "orderQty": 100}]}
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/market_maker/bitmex.py", line 263, in _curl_bitmex
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 773, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/marketmaker", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.4/dist-packages/market_maker/__init__.py", line 22, in run
    market_maker.run()
  File "/usr/local/lib/python3.4/dist-packages/market_maker/market_maker.py", line 543, in run
    om = OrderManager()
  File "/usr/local/lib/python3.4/dist-packages/market_maker/market_maker.py", line 220, in __init__
    self.reset()
  File "/usr/local/lib/python3.4/dist-packages/market_maker/market_maker.py", line 228, in reset
    self.place_orders()
  File "/usr/local/lib/python3.4/dist-packages/market_maker/market_maker.py", line 325, in place_orders
    return self.converge_orders(buy_orders, sell_orders)
  File "/usr/local/lib/python3.4/dist-packages/market_maker/market_maker.py", line 411, in converge_orders
    self.exchange.create_bulk_orders(to_create)
  File "/usr/local/lib/python3.4/dist-packages/market_maker/market_maker.py", line 193, in create_bulk_orders
    return self.bitmex.create_bulk_orders(orders)
  File "/usr/local/lib/python3.4/dist-packages/market_maker/bitmex.py", line 104, in wrapped
    return fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/market_maker/bitmex.py", line 178, in create_bulk_orders
    return self._curl_bitmex(path='order/bulk', postdict={'orders': orders}, verb='POST')
  File "/usr/local/lib/python3.4/dist-packages/market_maker/bitmex.py", line 342, in _curl_bitmex
    return retry()
  File "/usr/local/lib/python3.4/dist-packages/market_maker/bitmex.py", line 252, in retry
    raise Exception("Max retries on %s (%s) hit, raising." % (path, json.dumps(postdict or '')))
Exception: Max retries on order/bulk ({"orders": [{"symbol": "XBTUSD", "side": "Buy", "clOrdID": "mm_bitmex_VyNRaKV8Sz6w3Xohl7a7OQ", "price": 6561.5, "orderQty": 600}, {"symbol": "XBTUSD", "side": "Buy", "clOrdID": "mm_bitmex_8/TfEt7DRbi3FoOtJdBUBg", "price": 6594.5, "orderQty": 500}, {"symbol": "XBTUSD", "side": "Buy", "clOrdID": "mm_bitmex_2a+UkxN0TWOffHFO+Eznxg", "price": 6627.5, "orderQty": 400}, {"symbol": "XBTUSD", "side": "Buy", "clOrdID": "mm_bitmex_hBE/VSW4Rh2W8b0aMtZebg", "price": 6660.5, "orderQty": 300}, {"symbol": "XBTUSD", "side": "Buy", "clOrdID": "mm_bitmex_tFkC+nhLSA2/sV7TdjhUSg", "price": 6693.5, "orderQty": 200}, {"symbol": "XBTUSD", "side": "Buy", "clOrdID": "mm_bitmex_cs66szgqTyyESw3xkyCmAA", "price": 6727.0, "orderQty": 100}, {"symbol": "XBTUSD", "side": "Sell", "clOrdID": "mm_bitmex_AyHuL7DWSKGaAxgNdan8mQ", "price": 6966.0, "orderQty": 600}, {"symbol": "XBTUSD", "side": "Sell", "clOrdID": "mm_bitmex_IMbbVVIFRqmLQPU2L/uFPA", "price": 6931.0, "orderQty": 500}, {"symbol": "XBTUSD", "side": "Sell", "clOrdID": "mm_bitmex_TNXmjWg6TG+aS/qY3H8fhg", "price": 6896.5, "orderQty": 400}, {"symbol": "XBTUSD", "side": "Sell", "clOrdID": "mm_bitmex_Sxm9rbHsT3iCBudcZWp5rA", "price": 6862.5, "orderQty": 300}, {"symbol": "XBTUSD", "side": "Sell", "clOrdID": "mm_bitmex_HIA5dJu5S+KC6VFOYEkbXA", "price": 6828.5, "orderQty": 200}, {"symbol": "XBTUSD", "side": "Sell", "clOrdID": "mm_bitmex_SP8kQRcQSe2P6VANH29n2w", "price": 6794.5, "orderQty": 100}]}) hit, raising.
2018-06-21 10:59:56,900 - INFO - market_maker - Shutting down. All open orders will be cancelled.
2018-06-21 10:59:56,901 - INFO - market_maker - Resetting current position. Canceling all existing orders.
2018-06-21 10:59:56,901 - INFO - bitmex - sending req to https://testnet.bitmex.com/api/v1/order: {"count": 500, "filter": "{\"symbol\": \"XBTUSD\", \"ordStatus.isTerminated\": false}"}
2018-06-21 10:59:58,610 - INFO - ws_thread - Websocket Closed
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/market_maker/market_maker.py", line 497, in exit
    sys.exit()
SystemExit

**Comment by yupengzhi** [comment]
my python vertion is 3.4,version 3.5 or higher is needed.
