### ISSUE TITLE
Whats is the command line to execute custom strategy???

### ISSUE THREAD

**Issue by fefegit** [BitMEX/sample-market-maker#129]
Hi,

I have tried a lot but I cant finger out the command line to execute a custom strategy. Could someone help me?
Also how to configure different settings to run different strategies? I'm not understanding the command line logic.
Thanks for all the work!! Devs

**Comment by redanthrax** [comment]
clone the project into a directory.
Go into the directory.
If in linux run "python3 -m virtualenv env" while inside the directory to create the virtual env.
Then run "source env/activate" in order to start the virtual env.
Then run "pip install -r requirements.txt" to install the dependencies.
Then run "python3 marketmaker" or "python3 ./marketmaker" i cant remember which.
You might also have to copy the settings base file from the subdirectory to the main directory and rename it to settings.py and add your api keys to it since the setup command wasnt working for me and thats what i had to do.

**Comment by fefegit** [comment]
Tks for replying Gary but the problem is that always load the settings not what is in custom_strategy file.

**Comment by redanthrax** [comment]
So I copied custom_strategy.py to the top directory.

Changed the code up a bit like so.

`import sys

from market_maker.market_maker import OrderManager


class CustomOrderManager(OrderManager):
    """A sample order manager for implementing your own custom strategy"""

    def place_orders(self) -> None:
        # implement your custom strategy here

        buy_orders = []
        sell_orders = []

        # populate buy and sell orders, e.g.
        # buy_orders.append({'price': 999.0, 'orderQty': 100, 'side': "Buy"})
        # sell_orders.append({'price': 1001.0, 'orderQty': 100, 'side': "Sell"})

        buy_orders.append({'price': 999.0, 'orderQty': 100, 'side': "Buy"})
        sell_orders.append({'price': 1001.0, 'orderQty': 100, 'side': "Sell"})

        self.converge_orders(buy_orders, sell_orders)

    def run() -> None:
        order_manager = CustomOrderManager()

        # Try/except just keeps ctrl-c from printing an ugly stacktrace
        try:
            order_manager.run_loop()
        except (KeyboardInterrupt, SystemExit):
            sys.exit()


CustomOrderManager.run()`

I then start up the python virtualenv like so

`source env/bin/activate`

I then run python3 ./custom_strategy.py

**Comment by fefegit** [comment]
Tks. I will try it!

**Comment by fefegit** [comment]
Redanthrax,

Im getting a bunch of errors
`2018-07-07 22:07:31,955 - INFO - ws_thread - Connecting to wss://www.bitmex.com/realtime?subscribe=quote:XBTUSD,trade:XBTUSD,instrument,order:XBTUSD,execution:XBTUSD,margin,position
2018-07-07 22:07:31,955 - INFO - ws_thread - Authenticating with API Key.
2018-07-07 22:07:31,956 - INFO - ws_thread - Started thread
2018-07-07 22:07:33,957 - INFO - ws_thread - Connected to WS. Waiting for data images, this may take a moment...
2018-07-07 22:07:34,262 - INFO - ws_thread - Got all market data. Starting.
2018-07-07 22:07:34,262 - INFO - market_maker - Using symbol XBTUSD.
2018-07-07 22:07:34,263 - INFO - market_maker - Order Manager initializing, connecting to BitMEX. Live run: executing real trades.
2018-07-07 22:07:34,263 - INFO - market_maker - Resetting current position. Canceling all existing orders.
2018-07-07 22:07:34,264 - INFO - bitmex - sending req to https://www.bitmex.com/api/v1/order: {"filter": "{\"ordStatus.isTerminated\": false, \"symbol\": \"XBTUSD\"}", "count": 500}
Traceback (most recent call last):
  File "C:\ProgU\Python360\market_maker\bitmex.py", line 263, in _curl_bitmex
    response.raise_for_status()
  File "C:\ProgU\Python360\lib\site-packages\requests\models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://www.bitmex.com/api/v1/order?filter=%7B%22ordStatus.isTerminated%22%3A+false%2C+%22symbol%22%3A+%22XBTUSD%22%7D
unt=500

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgU\Python360\custom_strategy.py", line 34, in <module>
    CustomOrderManager.run()
  File "C:\ProgU\Python360\custom_strategy.py", line 25, in run
    order_manager = CustomOrderManager()
  File "C:\ProgU\Python360\market_maker\market_maker.py", line 220, in __init__
    self.reset()
  File "C:\ProgU\Python360\market_maker\market_maker.py", line 223, in reset
    self.exchange.cancel_all_orders()
  File "C:\ProgU\Python360\market_maker\market_maker.py", line 60, in cancel_all_orders
    orders = self.bitmex.http_open_orders()
  File "C:\ProgU\Python360\market_maker\bitmex.py", line 104, in wrapped
    return fn(self, *args, **kwargs)
  File "C:\ProgU\Python360\market_maker\bitmex.py", line 195, in http_open_orders
    verb="GET"
  File "C:\ProgU\Python360\market_maker\bitmex.py", line 342, in _curl_bitmex
    return retry()
  File "C:\ProgU\Python360\market_maker\bitmex.py", line 252, in retry
    raise Exception("Max retries on %s (%s) hit, raising." % (path, json.dumps(postdict or '')))
Exception: Max retries on order ("") hit, raising.
2018-07-07 22:07:35,317 - INFO - market_maker - Shutting down. All open orders will be cancelled.
2018-07-07 22:07:35,317 - INFO - market_maker - Resetting current position. Canceling all existing orders.
2018-07-07 22:07:35,318 - INFO - bitmex - sending req to https://www.bitmex.com/api/v1/order: {"filter": "{\"ordStatus.isTerminated\": false, \"symbol\": \"XBTUSD\"}", "count": 500}
2018-07-07 22:07:35,575 - INFO - market_maker - Unable to cancel orders: Max retries on order ("") hit, raising.

C:\ProgU\Python360>`

**Comment by redanthrax** [comment]
You need to create an api key on bitmex without the cancel option i think.

**Comment by pudong1** [comment]
Hi all, 

I followed  the instruction from @redanthrax, I indeed managed to place orders using my bitmex account via api key. But immediately it gave the following errors, see the snapshot below, any idea?
I appreciate if anyone could help!
 
![snipaste_2018-07-08_18-35-30](https://user-images.githubusercontent.com/40735848/42418947-c8f2c778-82dd-11e8-83e1-a92fb1cc6b6b.png)

**Comment by redanthrax** [comment]
Does it work on the testnet? I see youre making the request on the live market.

**Comment by pudong1** [comment]
@fegegit: Hi, have you solved your problem? I think I got the same problem as yours.

**Comment by AlexADittrich** [comment]
order size is too small, your small orders may be flagged as spam.  Order size needs to be at least 25 contracts

**Comment by yupengzhi** [comment]
the same problem

**Comment by yupengzhi** [comment]
chang bitmex.py 

#from market_maker.auth import APIKeyAuthWithExpires
from market_maker.auth import APIKeyAuth

...

# Auth: API Key/Secret
        #auth = APIKeyAuthWithExpires(self.apiKey, self.apiSecret)
        auth = APIKeyAuth(self.apiKey, self.apiSecret)

**Comment by pudong1** [comment]
@yupengzhi Thank you!

**Comment by yupengzhi** [comment]
class APIKeyAuthWithExpires(AuthBase):

    """Attaches API Key Authentication to the given Request object. This implementation uses `expires`."""

    def __init__(self, apiKey, apiSecret):
        """Init with Key & Secret."""
        self.apiKey = apiKey
        self.apiSecret = apiSecret

    def __call__(self, r):
        """
        Called when forming a request - generates api key headers. This call uses `expires` instead of nonce.

        This way it will not collide with other processes using the same API Key if requests arrive out of order.
        For more details, see https://www.bitmex.com/app/apiKeys
        """
        # modify and return the request
        expires = int(round(time.time()) + 5)  # 5s grace period in case of clock skew
        r.headers['api-expires'] = str(expires)
        r.headers['api-key'] = self.apiKey
        r.headers['api-signature'] = generate_signature(self.apiSecret, r.method, r.url, expires, r.body or '')

        return r


        expires = int(round(time.time() * 1000 ) + 5)  # 5s grace period in case of clock skew

**Comment by pudong1** [comment]
@yupengzhi Thank you very much!
