### ISSUE TITLE
Linear Instrument Calculation

### ISSUE THREAD

**Issue by tanaytrivedi** [BitMEX/sample-market-maker#13]
Hi,
Thanks for fixing my earlier request, I updated the files and that is now longer a problem. I now have another issue relating to calculation. 
```
ip-192-168-128-40:tryagain tanaytrivedi$ ./marketmaker
2017-07-07 16:51:19,091 - INFO - market_maker - BitMEX Market Maker Version: v1.1-18-g396b910

2017-07-07 16:51:19,092 - INFO - ws_thread - Connecting to wss://testnet.bitmex.com/realtime?subscribe=quote:EOSN17,trade:EOSN17,instrument,order:EOSN17,execution:EOSN17,margin,position
2017-07-07 16:51:19,092 - INFO - ws_thread - Authenticating with API Key.
2017-07-07 16:51:19,093 - INFO - ws_thread - Started thread
2017-07-07 16:51:20,094 - INFO - ws_thread - Connected to WS. Waiting for data images, this may take a moment...
2017-07-07 16:51:21,120 - INFO - ws_thread - Got all market data. Starting.
2017-07-07 16:51:21,120 - INFO - market_maker - Using symbol EOSN17.
2017-07-07 16:51:21,120 - INFO - market_maker - Order Manager initializing, connecting to BitMEX. Live run: executing real trades.
2017-07-07 16:51:21,121 - INFO - market_maker - Resetting current position. Cancelling all existing orders.
2017-07-07 16:51:22,555 - INFO - market_maker - EOSN17 Ticker: Buy: 0.00, Sell: 0.00
2017-07-07 16:51:22,556 - INFO - market_maker - Start Positions: Buy: 0.00, Sell: 0.00, Mid: 0.00
2017-07-07 16:51:22,556 - INFO - market_maker - Current XBT Balance: 3.256083
2017-07-07 16:51:22,556 - INFO - market_maker - Current Contract Position: -32
2017-07-07 16:51:22,556 - INFO - market_maker - Avg Cost Price: 0.00
2017-07-07 16:51:22,557 - INFO - market_maker - Avg Entry Price: 0.00
2017-07-07 16:51:22,557 - INFO - market_maker - Contracts Traded This Run: 0
Traceback (most recent call last):
  File "./marketmaker", line 4, in <module>
    market_maker.run()
  File "/Users/tanaytrivedi/Documents/GitHub/tryagain/market_maker/market_maker.py", line 543, in run
    om.init()
  File "/Users/tanaytrivedi/Documents/GitHub/tryagain/market_maker/market_maker.py", line 217, in init
    self.reset()
  File "/Users/tanaytrivedi/Documents/GitHub/tryagain/market_maker/market_maker.py", line 222, in reset
    self.print_status()
  File "/Users/tanaytrivedi/Documents/GitHub/tryagain/market_maker/market_maker.py", line 246, in print_status
    logger.info("Total Contract Delta: %.4f XBT" % self.exchange.calc_delta()['spot'])
  File "/Users/tanaytrivedi/Documents/GitHub/tryagain/market_maker/market_maker.py", line 97, in calc_delta
    portfolio = self.get_portfolio()
  File "/Users/tanaytrivedi/Documents/GitHub/tryagain/market_maker/market_maker.py", line 83, in get_portfolio
    multiplier = float(instrument['multiplier']) / float(instrument['underlyingToSettleMultiplier'])
TypeError: float() argument must be a string or a number
2017-07-07 16:51:22,559 - INFO - market_maker - Shutting down. All open orders will be cancelled.
2017-07-07 16:51:22,559 - INFO - market_maker - Resetting current position. Cancelling all existing orders.
2017-07-07 16:51:23,698 - INFO - ws_thread - Websocket Closed
```
It seems to me here that in the get_portfolio function the calculation is receiving some kind of error with data type.
Thanks for your help,
Tanay Trivedi

**Comment by arthurh3** [comment]
Please pull the latest version, that bug should now be fixed.
