### ISSUE TITLE
Unstable

### ISSUE THREAD

**Issue by chrism2671** [BitMEX/sample-market-maker#14]
So I've been experimenting with this, but I'm finding it's quite unstable and crashes a lot.

```
2017-08-16 15:13:37,647 - INFO - ws_thread - Execution: Sell 1500 Contracts of XBTUSD at 4239.9            [334/1871]
2017-08-16 15:13:40,077 - INFO - market_maker - XBTUSD Ticker: Buy: 4233.00, Sell: 4233.20
2017-08-16 15:13:40,078 - INFO - market_maker - Start Positions: Buy: 4230.98, Sell: 4235.22, Mid: 4233.10
2017-08-16 15:13:40,078 - INFO - market_maker - Current XBT Balance: 0.525952
2017-08-16 15:13:40,079 - INFO - market_maker - Current Contract Position: -41429
2017-08-16 15:13:40,079 - INFO - market_maker - Position limits: -100000/100000
2017-08-16 15:13:40,079 - INFO - market_maker - Avg Cost Price: 4205.21
2017-08-16 15:13:40,080 - INFO - market_maker - Avg Entry Price: 4205.21
2017-08-16 15:13:40,080 - INFO - market_maker - Contracts Traded This Run: -78824
2017-08-16 15:13:40,081 - INFO - market_maker - Total Contract Delta: -9.8523 XBT
2017-08-16 15:13:40,081 - INFO - market_maker - Creating 2 orders:
2017-08-16 15:13:40,082 - INFO - market_maker - Sell 1000 @ 4235.2
2017-08-16 15:13:40,082 - INFO - market_maker - Sell 1500 @ 4243.7
2017-08-16 15:13:43,087 - WARNING - bitmex - Timed out, retrying...
2017-08-16 15:13:45,626 - INFO - ws_thread - Execution: Sell 783 Contracts of XBTUSD at 4235.2
2017-08-16 15:13:45,628 - INFO - ws_thread - Execution: Sell 217 Contracts of XBTUSD at 4235.2
2017-08-16 15:13:46,169 - WARNING - bitmex - Timed out, retrying...
2017-08-16 15:13:49,249 - WARNING - bitmex - Timed out, retrying...
2017-08-16 15:13:50,365 - INFO - ws_thread - Execution: Sell 100 Contracts of XBTUSD at 4243.7
2017-08-16 15:13:50,466 - INFO - ws_thread - Execution: Sell 978 Contracts of XBTUSD at 4243.7
2017-08-16 15:13:50,510 - INFO - ws_thread - Execution: Sell 6 Contracts of XBTUSD at 4243.7
2017-08-16 15:13:51,031 - INFO - ws_thread - Execution: Sell 5 Contracts of XBTUSD at 4243.7
2017-08-16 15:13:52,126 - INFO - ws_thread - Execution: Sell 35 Contracts of XBTUSD at 4243.7
2017-08-16 15:13:52,330 - INFO - ws_thread - Execution: Sell 376 Contracts of XBTUSD at 4243.7
2017-08-16 15:13:52,330 - WARNING - bitmex - Timed out, retrying...
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 377, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 379, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.5/ssl.py", line 929, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.5/ssl.py", line 791, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.5/ssl.py", line 575, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 610, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 247, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 686, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 560, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 309, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='www.bitmex.com', port=443): Read tim
ed out. (read timeout=3)

During handling of the above exception, another exception occurred:                                        [263/1871]

Traceback (most recent call last):
  File "/home/chris/code/sample-market-maker/market_maker/bitmex.py", line 211, in _curl_bitmex
    response = self.session.send(prepped, timeout=timeout)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 449, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='www.bitmex.com', port=443): Read timed out. (read timeout=
3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 377, in _make_request
    httplib_response = conn.getresponse(buffering=True)
TypeError: getresponse() got an unexpected keyword argument 'buffering'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 379, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.5/ssl.py", line 929, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.5/ssl.py", line 791, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.5/ssl.py", line 575, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 610, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 247, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3/dist-packages/six.py", line 686, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 560, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 309, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
requests.packages.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='www.bitmex.com', port=443): Read tim
ed out. (read timeout=3)

This goes on a lot further.
```
Here's a different one:

```
2017-08-16 23:41:45,412 - INFO - market_maker -  Buy 3500 @ 4358.7
2017-08-16 23:41:45,460 - ERROR - bitmex - Error: 400 Client Error: Bad Request for url: https://www.bitmex.com/api/v
1/order/bulk: {"error":{"message":"Bulk orders: Order price is above the liquidation price of current short position"
,"name":"ValidationError"}}
2017-08-16 23:41:45,461 - ERROR - bitmex - Endpoint was: POST order/bulk: {"orders": [{"orderQty": 3500, "clOrdID": "
mm_bitmex_nC11SpgfRmSZ1N2cgGkh7g", "symbol": "XBTUSD", "price": 4358.7, "side": "Buy"}, {"orderQty": 3000, "clOrdID":
 "mm_bitmex_gBqkOjYfQuWTBzx9uFGUTw", "symbol": "XBTUSD", "price": 4367.5, "side": "Buy"}, {"orderQty": 2500, "clOrdID
": "mm_bitmex_y+bxQPfvT9Ww9lkMItcYkA", "symbol": "XBTUSD", "price": 4376.2, "side": "Buy"}, {"orderQty": 2000, "clOrd
ID": "mm_bitmex_rEv39rmMSjKe19M2AOPluQ", "symbol": "XBTUSD", "price": 4384.9, "side": "Buy"}, {"orderQty": 1500, "clO
rdID": "mm_bitmex_/EncAvL2R3SwtKUP8+1wNg", "symbol": "XBTUSD", "price": 4393.7, "side": "Buy"}, {"orderQty": 1000, "c
lOrdID": "mm_bitmex_nAMGtFIAT4CLQMAQ51goGw", "symbol": "XBTUSD", "price": 4402.5, "side": "Buy"}, {"orderQty": 3500, 
"clOrdID": "mm_bitmex_6etvwgWgTTGZNMZxZuKO3A", "symbol": "XBTUSD", "price": 4451.0, "side": "Sell"}, {"orderQty": 300
0, "clOrdID": "mm_bitmex_1Ds7I4BlTYO9TOTC7Ycxtg", "symbol": "XBTUSD", "price": 4442.2, "side": "Sell"}, {"orderQty": 
2500, "clOrdID": "mm_bitmex_S6zWBpMJT82PlF3FbCildg", "symbol": "XBTUSD", "price": 4433.3, "side": "Sell"}, {"orderQty
": 2000, "clOrdID": "mm_bitmex_qu3yO1nPSjuXRv01dxZP+A", "symbol": "XBTUSD", "price": 4424.4, "side": "Sell"}, {"order
Qty": 1500, "clOrdID": "mm_bitmex_GYzen6n5RnaQmKqQ47NVbQ", "symbol": "XBTUSD", "price": 4415.6, "side": "Sell"}, {"or
derQty": 1000, "clOrdID": "mm_bitmex_FKtiFuueRSOxlZfcIGKOwg", "symbol": "XBTUSD", "price": 4406.8, "side": "Sell"}]}
Traceback (most recent call last):
  File "marketmaker", line 4, in <module>
    market_maker.run()
  File "/home/chris/code/sample-market-maker/market_maker/market_maker.py", line 546, in run
    om.init()
  File "/home/chris/code/sample-market-maker/market_maker/market_maker.py", line 220, in init
    self.reset()
  File "/home/chris/code/sample-market-maker/market_maker/market_maker.py", line 228, in reset
    self.place_orders()
  File "/home/chris/code/sample-market-maker/market_maker/market_maker.py", line 325, in place_orders
    return self.converge_orders(buy_orders, sell_orders)
  File "/home/chris/code/sample-market-maker/market_maker/market_maker.py", line 411, in converge_orders
    self.exchange.create_bulk_orders(to_create)
  File "/home/chris/code/sample-market-maker/market_maker/market_maker.py", line 192, in create_bulk_orders
    return self.bitmex.create_bulk_orders(orders)
  File "/home/chris/code/sample-market-maker/market_maker/bitmex.py", line 97, in wrapped
    return function(self, *args, **kwargs)
  File "/home/chris/code/sample-market-maker/market_maker/bitmex.py", line 154, in create_bulk_orders
    return self._curl_bitmex(api='order/bulk', postdict={'orders': orders}, verb='POST')
  File "/home/chris/code/sample-market-maker/market_maker/bitmex.py", line 279, in _curl_bitmex
    raise e
  File "/home/chris/code/sample-market-maker/market_maker/bitmex.py", line 213, in _curl_bitmex
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 840, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://www.bitmex.com/api/v1/order/bulk
2017-08-16 23:41:45,504 - INFO - market_maker - Shutting down. All open orders will be cancelled.
2017-08-16 23:41:45,504 - INFO - market_maker - Resetting current position. Cancelling all existing orders.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/chris/code/sample-market-maker/market_maker/market_maker.py", line 497, in exit
    sys.exit()
SystemExit
```

The thing is, whatever happened, you take the greatest risk when the thing stops working. Is it possible to make these exceptions non-fatal?

**Comment by STRML** [comment]
The first is a timeout - perhaps you had network issues.

The second is an actual error you must address:

```
{"error":{"message":"Bulk orders: Order price is above the liquidation price of current short position"
,"name":"ValidationError"}}
```

**Comment by chrism2671** [comment]
I did spot that, however, I believe it would be a better solution to recover from these situations gracefully; in the case of situation 1- wait and retry, in the case of 2, seek to close position first.

The reason is that quitting in this way will leave you holding a position in the market, which can wipe out your account. If it has to terminate, the only safe way is after closing all positions.

I understand this is really just a demo so totally understand if improvements are not part of the plan.

**Comment by STRML** [comment]
Right, it's a demo. It's not intended to be a full-fledged market maker, just to demonstrate how you'd do some basic strategies, and to handle the websocket communications & API signing for you.

I appreciate the ideas but I don't want to encourage people to run this bot out of the box and think they're getting something resilient. It's a starting point.
