### ISSUE TITLE
Bad Request for Amend Orders

### ISSUE THREAD

**Issue by niranjan-harmony** [BitMEX/sample-market-maker#144]
Hi, I'm trying to amend orders but its throwing errors. Thoughts on how to solve this? I believe there is something wrong with the JSON format I'm sending.

2018-08-10 10:12:49,612 - INFO - bitmex - sending req to https://testnet.bitmex.com/api/v1/order: {"orderID": "fddbfd68-9d02-ef90-7cfb-401d777f0251", "orderQty": 1000, "price": 6346.0, "side": "Sell"}
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/market_maker/bitmex.py", line 339, in _curl_bitmex
    response.raise_for_status()
  File "/usr/local/lib/python3.7/site-packages/requests/models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://testnet.bitmex.com/api/v1/order

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/marketmaker", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.7/site-packages/market_maker/__init__.py", line 22, in run
    market_maker.run()
  File "/usr/local/lib/python3.7/site-packages/market_maker/market_maker.py", line 964, in run
    om.prepare_first_short_order()
  File "/usr/local/lib/python3.7/site-packages/market_maker/market_maker.py", line 626, in prepare_first_short_order
    self.prepare_short_order(qty, price)
  File "/usr/local/lib/python3.7/site-packages/market_maker/market_maker.py", line 728, in prepare_short_order
    self.order_short = self.exchange.amend_post_order(self.order_short, qty, price, orderID, leavesQty)
  File "/usr/local/lib/python3.7/site-packages/market_maker/market_maker.py", line 240, in amend_post_order
    return self.bitmex.amend_post_order(order, quantity, price, orderID, leavesQty)
  File "/usr/local/lib/python3.7/site-packages/market_maker/bitmex.py", line 104, in wrapped
    return fn(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/market_maker/bitmex.py", line 238, in amend_post_order
    return self._curl_bitmex(path=endpoint, postdict=postdict, verb='PUT', rethrow_errors=True)
  File "/usr/local/lib/python3.7/site-packages/market_maker/bitmex.py", line 418, in _curl_bitmex
    return retry()
  File "/usr/local/lib/python3.7/site-packages/market_maker/bitmex.py", line 328, in retry
    raise Exception("Max retries on %s (%s) hit, raising." % (path, json.dumps(postdict or '')))
Exception: Max retries on order ({"orderID": "fddbfd68-9d02-ef90-7cfb-401d777f0251", "orderQty": 1000, "price": 6346.0, "side": "Sell"}) hit, raising.
2018-08-10 10:12:49,774 - INFO - market_maker - Shutting down. All open orders will be cancelled.
2018-08-10 10:12:49,774 - INFO - market_maker - Resetting current position. Canceling all existing orders.
2018-08-10 10:12:49,774 - INFO - bitmex - sending req to https://testnet.bitmex.com/api/v1/order: {"filter": "{\"ordStatus.isTerminated\": false, \"symbol\": \"XBTUSD\"}", "count": 500}
2018-08-10 10:12:51,004 - INFO - ws_thread - Websocket Closed

**Comment by canokaue** [comment]
They aren't. I'm getting the same error here. 

Tested the amend_bulk_orders function independently and it seems to be broken .

**Comment by occocc** [comment]
line 237-238 bitmex.py 

```
 if max_retries is None:
    max_retries = 3 
```

 I changed the retry() so it does retry the post and put requests as well. This worked for me.
