### ISSUE TITLE
BitMEXWebsocket error

### ISSUE THREAD

**Issue by spoonwzd** [BitMEX/sample-market-maker#148]
I'm a new user trying to get Market Maker to work.

Have tried on both Ubuntu and Windows with Python v3.5 / 3.6 / 3.7 all with the same result:

```
2018-08-14 22:26:00,751 - INFO - market_maker - BitMEX Market Maker Version: v1.4

2018-08-14 22:26:00,766 - INFO - ws_thread - Connecting to wss://testnet.bitmex.com/realtime?subscribe=quote:XBTUSD,trade:XBTUSD,instrument,order:XBTUSD,execution:XBTUSD,margin,position
2018-08-14 22:26:00,766 - INFO - ws_thread - Authenticating with API Key.
2018-08-14 22:26:00,766 - INFO - ws_thread - Started thread
2018-08-14 22:26:01,001 - ERROR - _logging - error from callback <bound method BitMEXWebsocket.__on_open of <market_maker.ws.ws_thread.BitMEXWebsocket object at 0x000002317E1452E8>>: __on_open() missing 1 required positional argument: 'ws'
2018-08-14 22:26:01,001 - ERROR - _logging - error from callback <bound method BitMEXWebsocket.__on_message of <market_maker.ws.ws_thread.BitMEXWebsocket object at 0x000002317E1452E8>>: __on_message() missing 1 required positional argument: 'message'
```

...and then it repeats the missing positional argument line forever more.

My Google-fu is failing me. Anyone have any ideas?

**Comment by LF76** [comment]
I second this. Happens as above on Ubuntu 18.

**Comment by wschneller** [comment]
I third this, having the same problem on windows 10.

**Comment by strat123123** [comment]
Same for me on OSX El Capitan version 10.11.6.

**Comment by calimero26** [comment]
Same issue on macOS High Sierra 10.13.6, and Windows 10

**Comment by calimero26** [comment]
so it's just broken, and I assume nobody will/can fix ...

**Comment by noobsworld** [comment]
Same issue in Ubuntu 16.04/18.04, was working before , triggered when i made some changes to my config parameters not related to the web-socket, issues persists even if i revert my changes

**Comment by Cruisererick** [comment]
Any updates on this issue?

**Comment by meph1st0pheles** [comment]
For what it's worth, if you take a look at https://github.com/BitMEX/api-connectors/blob/master/official-ws/python/bitmex_websocket.py you'll see that there is a positional argument for 'message' on line 107.  Putting that into the ws_thread.py no longer gets the error above but now it's giving me the following error instead:

Traceback (most recent call last):
  File "/Users/wahabkazi/mm_test/sample-market-maker-master/market_maker/ws/ws_thread.py", line 38, in __del__
    self.exit()
  File "/Users/wahabkazi/mm_test/sample-market-maker-master/market_maker/ws/ws_thread.py", line 140, in exit
    self.ws.close()
AttributeError: 'BitMEXWebsocket' object has no attribute 'ws'

**Comment by wschneller** [comment]
I've gotten it fully working now on windows 10 using a conda enviroment with python 3.6. I'm pretty sure someone updated the pip installed version of the market-maker, but I'm new to github so I'm not entirely sure. Also i think the issue is a result of whatever bitmex websocket version is coming with the bitmex-market-maker pip install right now. Anyway, this is how I made it work

how to:
1.) create enviroment with python 3.6
2.) pip install bitmex-market-maker
3.) pip install bitmex-ws
4.) navigate to a working directory,  run 'marketmaker setup', update the settings.py file with your api info
5.) to run do 'marketmaker XBTUSD', not list format 'marketmaker [XBTUSD]' as mentioned in the getting started section

**Comment by oisinmacgiollachuda** [comment]
The [XBTUSD] part is an optional parameter (hence the square brackets), meaning if you leave it out it will run with the default (which is XBTUSD)

**Comment by spoonwzd** [comment]
The missing part was 'pip install bitmex-ws'

Thanks @wschneller !

**Comment by NogbadTheBad1** [comment]
> The missing part was 'pip install bitmex-ws'
> 
> Thanks @wschneller !

Yeah this is it. This should be in the readme. Thanks!

**Comment by AkshaySapra** [comment]
Im surprised they have resolved this issue yet in 2 years. Makes me wonder if they are capable of anything big. 'pip install bitmex-ws' is the easy solution.
