### ISSUE TITLE
Syntax Error during Dry Run

### ISSUE THREAD

**Issue by maxtimbo** [BitMEX/sample-market-maker#16]
I'm trying to run the commad:

`$ ./marketmaker XBTUSD`

which returns the following:

'Traceback (most recent call last):
  File "./marketmaker", line 3, in <module>
    from market_maker import market_maker
  File "/home/bitBot/sample-market-maker/market_maker/market_maker.py", line 11, in <module>
    from market_maker import bitmex
  File "/home/bitBot/sample-market-maker/market_maker/bitmex.py", line 12, in <module>
    from market_maker.ws.ws_thread import BitMEXWebsocket
  File "/home/bitBot/sample-market-maker/market_maker/ws/ws_thread.py", line 104
    return {k: round(float(v or 0), instrument['tickLog']) for k, v in iteritems(ticker)}
                                                             ^
SyntaxError: invalid syntax'

I'm assuming I don't have the correct dependencies installed. If that is not the issue, than what have I missed?

**Comment by STRML** [comment]
Make sure you run with Python 3.

**Comment by ryanfox** [comment]
Can't reproduce in either 2 or 3. Closing absent any other information.
