### ISSUE TITLE
Getting "Access Denied" error when running marketmaker

### ISSUE THREAD

**Issue by mirvine** [BitMEX/sample-market-maker#20]
HI, 

I'm getting "Access Denied" error. I created my API key on the testnet with "orderCancel" permissions.

Running with python2 on Mac.

Log shows:

2017-10-26 18:02:31,244 - ERROR - bitmex - Error: 403 Client Error: Forbidden for url: https://testnet.bitmex.com/api/v1/order/bulk: {"error":{"message":"Access Denied","name":"Error"}}
2017-10-26 18:02:31,244 - ERROR - bitmex - Endpoint was: POST order/bulk: {"orders": [{"symbol": "XBTUSD", "price": 5906.5, "orderQty": 10, "side": "Buy", "clOrdID": "mm_bitmex_fZI7kBSpQ6KZQsjONtaGhw"}, {"symbol": "XBTUSD", "price": 5965.8, "orderQty": 10, "side": "Sell", "clOrdID": "mm_bitmex_KS/Ta+XjT4SsgJZJg81qYg"}]}
Traceback (most recent call last):
  File "./marketmaker", line 4, in <module>
    market_maker.run()
  File "/Users/admin/Documents/Projects/Mark/traderjoe/mmaker/sample-market-maker-master/market_maker/market_maker.py", line 546, in run
    om.init()
  File "/Users/admin/Documents/Projects/Mark/traderjoe/mmaker/sample-market-maker-master/market_maker/market_maker.py", line 220, in init
    self.reset()
  File "/Users/admin/Documents/Projects/Mark/traderjoe/mmaker/sample-market-maker-master/market_maker/market_maker.py", line 228, in reset
    self.place_orders()
  File "/Users/admin/Documents/Projects/Mark/traderjoe/mmaker/sample-market-maker-master/market_maker/market_maker.py", line 325, in place_orders
    return self.converge_orders(buy_orders, sell_orders)
  File "/Users/admin/Documents/Projects/Mark/traderjoe/mmaker/sample-market-maker-master/market_maker/market_maker.py", line 411, in converge_orders
    self.exchange.create_bulk_orders(to_create)
  File "/Users/admin/Documents/Projects/Mark/traderjoe/mmaker/sample-market-maker-master/market_maker/market_maker.py", line 192, in create_bulk_orders
    return self.bitmex.create_bulk_orders(orders)
  File "/Users/admin/Documents/Projects/Mark/traderjoe/mmaker/sample-market-maker-master/market_maker/bitmex.py", line 97, in wrapped
    return function(self, *args, **kwargs)
  File "/Users/admin/Documents/Projects/Mark/traderjoe/mmaker/sample-market-maker-master/market_maker/bitmex.py", line 154, in create_bulk_orders
    return self._curl_bitmex(api='order/bulk', postdict={'orders': orders}, verb='POST')
  File "/Users/admin/Documents/Projects/Mark/traderjoe/mmaker/sample-market-maker-master/market_maker/bitmex.py", line 280, in _curl_bitmex
    raise e
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://testnet.bitmex.com/api/v1/order/bulk
2017-10-26 18:02:31,245 - INFO - market_maker - Shutting down. All open orders will be cancelled.
2017-10-26 18:02:31,246 - INFO - market_maker - Resetting current position. Cancelling all existing orders.
2017-10-26 18:02:32,298 - INFO - ws_thread - Websocket Closed

**Comment by STRML** [comment]
From the API Key page where you generated that key:

> Set "Order Cancel" to allow *only* canceling orders. Do not combine with "Order".

**Comment by mirvine** [comment]
Ah! Misread that instruction. Working now. Thanks
