### ISSUE TITLE
ImportError: cannot import name 'run' from 'market_maker' 

### ISSUE THREAD

**Issue by MedokD** [BitMEX/sample-market-maker#204]
Hi all!
I am stacked while installing marketmaker. Can somebody help me to understand this problem?

\python-virtual-environments>marketmaker setup
Traceback (most recent call last):
  File "programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "Programs\Python\Python37\Scripts\marketmaker.exe\__main__.py", line 4, in <module>
ImportError: cannot import name 'run' from 'market_maker' (programs\python\python37\market_maker\__init__.py)

Looks like problem is the init file, but i am new in Py so maybe i am losing something important

**Comment by MedokD** [comment]
Ok, I installed marketmaker, adjusted settings but still getting the same Error
