### ISSUE TITLE
Sample market maker not starting

### ISSUE THREAD

**Issue by ken4ward** [BitMEX/sample-market-maker#207]
This is my first time trying to start this sample market maker. It gives this error after issuing this command - `marketmaker ['XBTUSD']`. What can I do?

```
Traceback (most recent call last):
  File "/usr/local/bin/marketmaker", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python2.7/site-packages/market_maker/__init__.py", line 21, in run
    from market_maker import market_maker
  File "/usr/local/lib/python2.7/site-packages/market_maker/market_maker.py", line 11, in <module>
    from market_maker import bitmex
  File "/usr/local/lib/python2.7/site-packages/market_maker/bitmex.py", line 12, in <module>
    from market_maker.ws.ws_thread import BitMEXWebsocket
  File "/usr/local/lib/python2.7/site-packages/market_maker/ws/ws_thread.py", line 10, in <module>
    from market_maker.settings import settings
  File "/usr/local/lib/python2.7/site-packages/market_maker/settings.py", line 25, in <module>
    userSettings = import_path(os.path.join('.', 'settings'))
  File "/usr/local/lib/python2.7/site-packages/market_maker/settings.py", line 20, in import_path
    importlib.reload(module)  # Might be out of date
AttributeError: 'module' object has no attribute 'reload'
```

**Comment by STRML** [comment]
This message:
```
2019-12-24 03:40:45,384 - ERROR - bitmex - Unhandled Error: 400 Client Error: Bad Request for url: https://testnet.bitmex.com/api/v1/order?filter=%7B%22ordStatus.isTerminated%22%3A+false%2C+%22symbol%22%3A+%22XBTUSD%22%7D&count=500: {"error":{"message":"This request has expired - `expires` is in the past. Current time: 1577155257","name":"HTTPError"}}
```

Indicates that your clock is skewed from the server. Please make sure that your clock is correctly set, and use network time if your OS supports it.
