### ISSUE TITLE
Problem starting the Code without any change (Import problems?)

### ISSUE THREAD

**Issue by cwk1ng** [BitMEX/sample-market-maker#212]
I don't really understand why I can't run the code. I didnt change anything yet and just wanted to see how the bot is working, but:

When I run the marketmaker.py I get this Error:
`Exception has occurred: ImportError
cannot import name 'bitmex' from partially initialized module 'market_maker' (most likely due to a circular import) (c:\Users\han_m\Documents\Visual Studio Code\sample-market-maker-master\market_maker\market_maker.py)
  File "C:\Users\han_m\Documents\Visual Studio Code\sample-market-maker-master\market_maker\market_maker.py", line 11, in <module>
    from market_maker import bitmex
  File "C:\Users\han_m\Documents\Visual Studio Code\sample-market-maker-master\market_maker\market_maker.py", line 11, in <module>
    from market_maker import bitmex`

When I run the marketmaker.py I get this Error:

`Traceback (most recent call last):
  File "c:\Users\han_m\.vscode\extensions\ms-python.python-2020.2.64397\pythonFiles\ptvsd_launcher.py", line 48, in <module>
    main(ptvsdArgs)
  File "c:\Users\han_m\.vscode\extensions\ms-python.python-2020.2.64397\pythonFiles\lib\python\old_ptvsd\ptvsd\__main__.py", line 432, in main
    run()
  File "c:\Users\han_m\.vscode\extensions\ms-python.python-2020.2.64397\pythonFiles\lib\python\old_ptvsd\ptvsd\__main__.py", line 316, in run_file
    runpy.run_path(target, run_name='__main__')
  File "C:\Users\han_m\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 263, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\han_m\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\han_m\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\Users\han_m\Documents\Visual Studio Code\sample-market-maker-master\marketmaker", line 3, in <module>
    from market_maker import market_maker
  File "c:\Users\han_m\Documents\Visual Studio Code\sample-market-maker-master\market_maker\market_maker.py", line 11, in <module>
    from market_maker import bitmex
  File "c:\Users\han_m\Documents\Visual Studio Code\sample-market-maker-master\market_maker\bitmex.py", line 12, in <module>
    from market_maker.ws.ws_thread import BitMEXWebsocket
  File "c:\Users\han_m\Documents\Visual Studio Code\sample-market-maker-master\market_maker\ws\ws_thread.py", line 10, in <module>
    from market_maker.settings import settings
  File "c:\Users\han_m\Documents\Visual Studio Code\sample-market-maker-master\market_maker\settings.py", line 25, in <module>
    userSettings = import_path(os.path.join('.', 'settings'))
  File "c:\Users\han_m\Documents\Visual Studio Code\sample-market-maker-master\market_maker\settings.py", line 19, in import_path
    module = importlib.import_module(filename, path)
  File "C:\Users\han_m\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'settings'`

I have these Errors also:
https://i.ibb.co/L6NpzG5/undef.jpg
So there is no "settings.ANYTHINGHERE" found. Think there is a problem with the imports, but since I didnt change any code I dont know why?

Thanks in advance

**Comment by ChuckNorrison** [comment]
same here... with python3.6 there is a missing module "future"
