### ISSUE TITLE
Cannot Import name "BITMEX" from Partially initialized module 'market_maker'

### ISSUE THREAD

**Issue by cnewhouse3** [BitMEX/sample-market-maker#231]
runfile('C:/Users/Christopher/.conda/envs/Market Maker Environment/Lib/site-packages/market_maker/market_maker.py', wdir='C:/Users/Christopher/.conda/envs/Market Maker Environment/Lib/site-packages/market_maker')
Traceback (most recent call last):

  File "C:\Users\Christopher\.conda\envs\Market Maker Environment\Lib\site-packages\market_maker\market_maker.py", line 11, in <module>
    from market_maker import bitmex

  File "C:\Users\Christopher\.conda\envs\Market Maker Environment\Lib\site-packages\market_maker\market_maker.py", line 11, in <module>
    from market_maker import bitmex

ImportError: cannot import name 'bitmex' from partially initialized module 'market_maker' (most likely due to a circular import) (C:\Users\Christopher\.conda\envs\Market Maker Environment\Lib\site-packages\market_maker\market_maker.py)

**Comment by mistersfunk** [comment]
i get the same thing
