### ISSUE TITLE
getting error":{"message":"Invalid price tickSize","name":"HTTPError"}}

### ISSUE THREAD

**Issue by mirvine** [BitMEX/sample-market-maker#24]
I've been operating this bot on the test net for the last couple of days. Noticed today it started failing. Any idea why it started failing? What does 'Invalid price tickSize' mean? Is that the price of  7290.3 or the orderQty of 285.0.

2017-11-04 22:25:39,591 - INFO - market_maker -  Buy 285 @ 7290.3
2017-11-04 22:25:39,640 - ERROR - bitmex - Error: 400 Client Error: Bad Request for url: https://testnet.bitmex.com/api/v1/order/bulk: {"error":{"message":"Invalid price tickSize","name":"HTTPError"}}
2017-11-04 22:25:39,642 - ERROR - bitmex - Endpoint was: POST order/bulk: {"orders": [{"symbol": "XBTUSD", "price": 7290.3, "orderQty": 285.0, "side": "Buy", "clOrdID": "mm_bitmex_kHgl4pzURu2h/bjFujJzlA"}, {"symbol": "XBTUSD", "price": 7326.8, "orderQty": 235.0, "side": "Buy", "clOrdID": "mm_bitmex_ldk+C3hNT2isCqR7Z0kuRg"}, {"symbol": "XBTUSD", "price": 7363.4, "orderQty": 185.0, "side": "Buy", "clOrdID": "mm_bitmex_p0YXwlQpTA6DcwYBAhhHcg"}, {"symbol": "XBTUSD", "price": 7400.2, "orderQty": 135.0, "side": "Buy", "clOrdID": "mm_bitmex_vqwj3R3oRt2gtuMKWSFTlw"}]}
Traceback (most recent call last):
  File "/mnt/mm2/marketmaker", line 4, in <module>
    market_maker.run()
  File "/mnt/mm2/market_maker/market_maker.py", line 617, in run
    om.init()
  File "/mnt/mm2/market_maker/market_maker.py", line 225, in init
    self.reset()
  File "/mnt/mm2/market_maker/market_maker.py", line 233, in reset
    self.place_orders()
  File "/mnt/mm2/market_maker/market_maker.py", line 363, in place_orders
    return self.converge_orders(buy_orders, sell_orders)
  File "/mnt/mm2/market_maker/market_maker.py", line 451, in converge_orders
    self.exchange.create_bulk_orders(to_create)
  File "/mnt/mm2/market_maker/market_maker.py", line 196, in create_bulk_orders
    return self.bitmex.create_bulk_orders(orders)
  File "/mnt/mm2/market_maker/bitmex.py", line 97, in wrapped
    return function(self, *args, **kwargs)
  File "/mnt/mm2/market_maker/bitmex.py", line 154, in create_bulk_orders
    return self._curl_bitmex(api='order/bulk', postdict={'orders': orders}, verb='POST')
  File "/mnt/mm2/market_maker/bitmex.py", line 280, in _curl_bitmex
    raise e

**Comment by STRML** [comment]
We are testing an update to the trading engine that will set the minimum tick to 0.5 (from 0.1). You must make sure your orders are only set by that tick. I'll take a look at this project as it should be doing it automatically.

**Comment by mirvine** [comment]
Ok, I made a change here to stick to 0.5 tick and it's working again now. Thanks for the quick response.

**Comment by mirvine** [comment]
Any idea when that change will be applied to live trading engine?

**Comment by STRML** [comment]
We are planning on Thursday. We'll do an announcement shortly. I've updated this repository to respect the `tickSize` correctly (issue is that the new tick is not a power of 10, which is not a safe assumption to make).

**Comment by biahoi** [comment]
> We are testing an update to the trading engine that will set the minimum tick to 0.5 (from 0.1). You must make sure your orders are only set by that tick. I'll take a look at this project as it should be doing it automatically.

I am sorry for a stupid question, but what is TickSize and how to set it? Thank you.
