### ISSUE TITLE
Error updating order book with more than 100 entries a time

### ISSUE THREAD

**Issue by Utfard** [BitMEX/sample-market-maker#28]
Hello , 
On November 12th Bitmex updated their policy regarding the number of orders submitted a time to 100.

> Starting November 12, 2017, at 12:00 UTC, the API will limit calls to bulk order endpoints to a maximum count of 100. Calls with a larger number of orders will be rejected with a status code of 400 and the message Too many orders provided. The maximum count allowed is 100.
[https://blog.bitmex.com/api_announcement/limits-to-bulk-order-endpoints/](url)

Therefore, on rush moments the script stops working. Please find below the output.

`017-11-16 09:51:48,956 - INFO - ws_thread - Execution: Sell 22 Contracts of XBTUSD at 7418.0
2017-11-16 09:51:48,961 - INFO - ws_thread - Execution: Sell 12 Contracts of XBTUSD at 7410.5
2017-11-16 09:51:48,966 - INFO - ws_thread - Execution: Sell 2 Contracts of XBTUSD at 7403.0
2017-11-16 09:51:49,563 - INFO - ws_thread - Execution: Sell 32 Contracts of XBTUSD at 7424.0
2017-11-16 09:51:51,916 - INFO - market_maker - XBTUSD Ticker: Buy: 7421.0, Sell: 7421.5
2017-11-16 09:51:51,916 - INFO - market_maker - Start Positions: Buy: 7410.4, Sell: 7432.1, Mid: 7421.5
2017-11-16 09:51:51,917 - INFO - market_maker - Current XBT Balance: 0.004284
2017-11-16 09:51:51,917 - INFO - market_maker - Current Contract Position: -444
2017-11-16 09:51:51,917 - INFO - market_maker - Avg Cost Price: 7355.1
2017-11-16 09:51:51,917 - INFO - market_maker - Avg Entry Price: 7355.1
2017-11-16 09:51:51,917 - INFO - market_maker - Contracts Traded This Run: -400
2017-11-16 09:51:51,917 - INFO - market_maker - Total Contract Delta: -0.0604 XBT
2017-11-16 09:51:51,918 - INFO - market_maker - Amending  Buy: 2 @ 7328.5 to 2 @ 7410.5 (+82.0)
2017-11-16 09:51:51,918 - INFO - market_maker - Amending  Buy: 12 @ 7321.0 to 12 @ 7403.0 (+82.0)
2017-11-16 09:51:51,919 - INFO - bitmex - sending req to https://www.bitmex.com/api/v1/order/bulk: {"orders": [{"orderID": "2b004aa2-28f7-1865-8b2c-645252310b44", "price": 7403.0, "orderQty": 12, "side": "Buy"}, {"orderID": "41707f41-091e-7eb8-a5f7-a0b0cf89b2d9", "price": 7410.5, "orderQty": 2, "side": "Buy"}]}
2017-11-16 09:51:56,928 - WARNING - bitmex - Timed out on request: order/bulk ({"orders": [{"orderID": "2b004aa2-28f7-1865-8b2c-645252310b44", "price": 7403.0, "orderQty": 12, "side": "Buy"}, {"orderID": "41707f41-091e-7eb8-a5f7-a0b0cf89b2d9", "price": 7410.5, "orderQty": 2, "side": "Buy"}]}), retrying...
Traceback (most recent call last):
  File "./marketmaker", line 4, in <module>
    market_maker.run()
  File "/home/muthabor/git/sample-market-maker/market_maker/market_maker.py", line 550, in run
    om.run_loop()
  File "/home/muthabor/git/sample-market-maker/market_maker/market_maker.py", line 518, in run_loop
    self.place_orders()  # Creates desired orders and converges to existing orders
  File "/home/muthabor/git/sample-market-maker/market_maker/market_maker.py", line 328, in place_orders
    return self.converge_orders(buy_orders, sell_orders)
  File "/home/muthabor/git/sample-market-maker/market_maker/market_maker.py", line 399, in converge_orders
    self.exchange.amend_bulk_orders(to_amend)
  File "/home/muthabor/git/sample-market-maker/market_maker/market_maker.py", line 187, in amend_bulk_orders
    return self.bitmex.amend_bulk_orders(orders)
  File "/home/muthabor/git/sample-market-maker/market_maker/bitmex.py", line 102, in wrapped
    return fn(self, *args, **kwargs)
  File "/home/muthabor/git/sample-market-maker/market_maker/bitmex.py", line 166, in amend_bulk_orders
    return self._curl_bitmex(path='order/bulk', postdict={'orders': orders}, verb='PUT', rethrow_errors=True)
  File "/home/muthabor/git/sample-market-maker/market_maker/bitmex.py", line 346, in _curl_bitmex
    return retry()
  File "/home/muthabor/git/sample-market-maker/market_maker/bitmex.py", line 247, in retry
    raise Exception("Max retries on %s (%s) hit, raising." % (path, json.dumps(postdict or '')))
Exception: Max retries on order/bulk ({"orders": [{"orderID": "2b004aa2-28f7-1865-8b2c-645252310b44", "price": 7403.0, "orderQty": 12, "side": "Buy"}, {"orderID": "41707f41-091e-7eb8-a5f7-a0b0cf89b2d9", "price": 7410.5, "orderQty": 2, "side": "Buy"}]}) hit, raising.
2017-11-16 09:51:56,955 - INFO - market_maker - Shutting down. All open orders will be cancelled.
2017-11-16 09:51:56,956 - INFO - market_maker - Resetting current position. Canceling all existing orders.
2017-11-16 09:51:56,956 - INFO - bitmex - sending req to https://www.bitmex.com/api/v1/order: {"filter": "{\"ordStatus.isTerminated\": false, \"symbol\": \"XBTUSD\"}", "count": 500}
2017-11-16 09:51:57,223 - INFO - market_maker - Canceling: Buy 42 @ 7315.5
2017-11-16 09:51:57,223 - INFO - market_maker - Canceling: Buy 32 @ 7326.0
2017-11-16 09:51:57,223 - INFO - market_maker - Canceling: Buy 22 @ 7330.5
2017-11-16 09:51:57,223 - INFO - market_maker - Canceling: Buy 12 @ 7403.0
2017-11-16 09:51:57,223 - INFO - market_maker - Canceling: Buy 2 @ 7410.5
2017-11-16 09:51:57,223 - INFO - market_maker - Canceling: Sell 42 @ 7431.0
2017-11-16 09:51:57,224 - INFO - bitmex - sending req to https://www.bitmex.com/api/v1/order: {"orderID": ["5b901309-0c19-22cb-6643-1076c1fa26df", "54b0876b-2614-e56c-4ee0-95b6e8718af0", "2ea229ad-ce78-8578-eb40-3ba09eac2f2c", "2b004aa2-28f7-1865-8b2c-645252310b44", "41707f41-091e-7eb8-a5f7-a0b0cf89b2d9", "5b88cc1e-5eb9-8b9b-d3c6-620dd906f0f4"]}

`

**Comment by STRML** [comment]
That's not the issue - you're only submitting 2 orders at that time. Try increasing the timeout.

**Comment by andy1245** [comment]
I have the same issue from time to time. Where do I have to increase the timeout value? Which file?

Sometimes I get - WARNING - bittmex - Unable to contact the BitEX API (503) . What can i do to prevent this error. Is there a value to increase to retrys?

Thanks for your help.

**Comment by dmh181** [comment]
anyone suggests the solution for this issue. How to increase the timeout value?

**Comment by ryanfox** [comment]
You can specify `TIMEOUT` in settings.py on the dev branch.

**Comment by ryanfox** [comment]
And now the `TIMEOUT` setting is supported on master and the version on PyPI. Closing.
