### ISSUE TITLE
ModuleNotFoundError: No module named 'settings'

### ISSUE THREAD

**Issue by klaasv12** [BitMEX/sample-market-maker#34]
> RESTART: \bitmex\sample-market-maker-master\market_maker.py 
Traceback (most recent call last):
  File "\bitmex\sample-market-maker-master\market_maker.py", line 11, in <module>
    from market_maker import bitmex
  File "\bitmex\sample-market-maker-master\market_maker\bitmex.py", line 12, in <module>
    from market_maker.ws.ws_thread import BitMEXWebsocket
  File "\bitmex\sample-market-maker-master\market_maker\ws\ws_thread.py", line 10, in <module>
    from market_maker.settings import settings
  File "\bitmex\sample-market-maker-master\market_maker\settings.py", line 22, in <module>
    userSettings = import_path(os.path.join('..', 'settings'))
  File "\bitmex\sample-market-maker-master\market_maker\settings.py", line 17, in import_path
    module = __import__(filename)
ModuleNotFoundError: No module named 'settings'
>>> 

Any idea what I am doing wrong

**Comment by ShervinDD** [comment]
[Don't forget to execute this in the command line:](https://www.reddit.com/r/BitMEX/comments/70w0su/trying_to_run_sample_market_maker_bot/) `python setup.py install `

**Comment by ryanfox** [comment]
That is the right answer, make sure you run `python setup.py install`. That will create `settings.py` in the project directory. Closing.
