### ISSUE TITLE
Orders don't stay open for long

### ISSUE THREAD

**Issue by lee101** [BitMEX/sample-market-maker#39]
An improvement to this bot would be to help the orders stay open for longer or only cancel them at the last minute to give the orders a higher probability of executing. (reducing the amount of time that there are no orders open in the market)

For now i have been increasing the sleep interval so it sleeps longer and thus leaves orders open for longer in the market.

May get time to do this in my fork which adds support for forecasts at https://github.com/BitBanknz/sample-market-maker

Thanks.

Kind Regards,
Lee - Founder

**Comment by STRML** [comment]
I'm unsure what you're actually asking here. This bot opens orders then amends them over time. They are not canceled & replaced.

**Comment by lee101** [comment]
Sorry was completely my fault.
i was running this with the linux timeout and watch command which was restarting too much, now i'm running with a simple bash loop instead e.g. `while true; do timeout --signal=KILL 1000 ./marketmaker ETHZ17; done`

**Comment by STRML** [comment]
Why are you running it in a loop at all?

**Comment by lee101** [comment]
Just had a few crashes and wanted to ensure it keeps running/restarts if there's an exception thrown, restarting it out every 1000 seconds is probably a bit over the top but i _think_ i had a case where it was still running but not doing anything.

Looking over the logs i can see the odd exception, i'm not sure how it would have handled them without the restart, Looks like maybe it restarted okay after that one.

Sorry i don't have more details, mostly paranoia really

```
bitmex - sending req to https://www.bitmex.com/api/v1/order/bulk: {"orders": [{"orderID": "8983df61-accc-2ac8-e021-6ff0370e707e", "price": 0.04692, "orderQty": 1, "side": "Sell"}, {"orderID": "aeac7a3a-d3a8-f5cf-5da3-793c6ea9f052", "price": 0.04668, "orderQty": 1, "side": "Sell"}]}
2017-12-20 01:25:14,131 - WARNING - bitmex - Unable to contact the BitMEX API (503), retrying. Request: https://www.bitmex.com/api/v1/order/bulk 
 {"orders": [{"orderID": "8983df61-accc-2ac8-e021-6ff0370e707e", "price": 0.04692, "orderQty": 1, "side": "Sell"}, {"orderID": "aeac7a3a-d3a8-f5cf-5da3-793c6ea9f052", "price": 0.04668, "orderQty": 1, "side": "Sell"}]}
Traceback (most recent call last):
  File "./marketmaker", line 4, in <module>
    market_maker.run()
  File "/home/lee/code/sample-market-maker/market_maker/market_maker.py", line 555, in run
    om.run_loop()
  File "/home/lee/code/sample-market-maker/market_maker/market_maker.py", line 520, in run_loop
    self.place_orders()  # Creates desired orders and converges to existing orders
  File "/home/lee/code/sample-market-maker/market_maker/market_maker.py", line 331, in place_orders
    return self.converge_orders(buy_orders, sell_orders)
  File "/home/lee/code/sample-market-maker/market_maker/market_maker.py", line 402, in converge_orders
    self.exchange.amend_bulk_orders(to_amend)
  File "/home/lee/code/sample-market-maker/market_maker/market_maker.py", line 187, in amend_bulk_orders
    return self.bitmex.amend_bulk_orders(orders)
  File "/home/lee/code/sample-market-maker/market_maker/bitmex.py", line 102, in wrapped
    return fn(self, *args, **kwargs)
  File "/home/lee/code/sample-market-maker/market_maker/bitmex.py", line 166, in amend_bulk_orders
    return self._curl_bitmex(path='order/bulk', postdict={'orders': orders}, verb='PUT', rethrow_errors=True)
  File "/home/lee/code/sample-market-maker/market_maker/bitmex.py", line 308, in _curl_bitmex
    return retry()
  File "/home/lee/code/sample-market-maker/market_maker/bitmex.py", line 247, in retry
    raise Exception("Max retries on %s (%s) hit, raising." % (path, json.dumps(postdict or '')))
Exception: Max retries on order/bulk ({"orders": [{"orderID": "8983df61-accc-2ac8-e021-6ff0370e707e", "price": 0.04692, "orderQty": 1, "side": "Sell"}, {"orderID": "aeac7a3a-d3a8-f5cf-5da3-793c6ea9f052", "price": 0.04668, "orderQty": 1, "side": "Sell"}]}) hit, raising.
```

**Comment by STRML** [comment]
Why don't you just monitor it using any sort of uptime tool (forever, supervisord, monit... there are dozens).

Those 503s are overload messages. You can work around them by putting in some retry logic for that message specifically.

**Comment by lee101** [comment]
Yes that a better idea, i did something slightly more elaborate than supervisorctl/timeout for the BitBank.nz forecaster, it has a manager process that listens for progress updates from the forecaster so it doesn't get restarted if it doesn't have to be.

I did run into a situation recently that was fixed by restarting: it was perhaps a network issue where it would hang when first connecting to bitmex, when i restarted it came right and printed
```
Traceback (most recent call last):
2017-12-22 05:57:02,227 - ERROR - ws_thread - (4, 'Interrupted system call')
  File "./marketmaker", line 4, in <module>
    market_maker.run()
  File "/home/lee/code/sample-market-maker/market_maker/market_maker.py", line 569, in run
    om = OrderManager()
  File "/home/lee/code/sample-market-maker/market_maker/market_maker.py", line 202, in __init__
    self.exchange = ExchangeInterface(settings.DRY_RUN)
  File "/home/lee/code/sample-market-maker/market_maker/market_maker.py", line 35, in __init__
    orderIDPrefix=settings.ORDERID_PREFIX, postOnly=settings.POST_ONLY)
  File "/home/lee/code/sample-market-maker/market_maker/bitmex.py", line 47, in __init__
    self.ws.connect(base_url, symbol, shouldAuth=shouldWSAuth)
  File "/home/lee/code/sample-market-maker/market_maker/ws/ws_thread.py", line 67, in connect
    self.__wait_for_account()
  File "/home/lee/code/sample-market-maker/market_maker/ws/ws_thread.py", line 197, in __wait_for_account
    sleep(0.1)
```
