### ISSUE TITLE
No module named 'settings'

### ISSUE THREAD

**Issue by ec-mr-anderson** [BitMEX/sample-market-maker#41]
I am getting the following error when run marketmaker.  I am using Python 3.6.  Any help is appreciated.

oracle@segfault::/home/oracle/git/sample-market-maker> ./marketmaker 
Traceback (most recent call last):
  File "./marketmaker", line 3, in <module>
    from market_maker import market_maker
  File "/home/oracle/git/sample-market-maker/market_maker/market_maker.py", line 11, in <module>
    from market_maker import bitmex
  File "/home/oracle/git/sample-market-maker/market_maker/bitmex.py", line 12, in <module>
    from market_maker.ws.ws_thread import BitMEXWebsocket
  File "/home/oracle/git/sample-market-maker/market_maker/ws/ws_thread.py", line 10, in <module>
    from market_maker.settings import settings
  File "/home/oracle/git/sample-market-maker/market_maker/settings.py", line 22, in <module>
    userSettings = import_path(os.path.join('..', 'settings'))
  File "/home/oracle/git/sample-market-maker/market_maker/settings.py", line 17, in import_path
    module = __import__(filename)
ModuleNotFoundError: No module named 'settings'
oracle@segfault::/home/oracle/git/sample-market-maker> pip3.6 freeze
certifi==2017.11.5
chardet==3.0.4
future==0.16.0
idna==2.6
psycopg2==2.7.3.2
requests==2.18.4
six==1.11.0
urllib3==1.22
websocket-client==0.45.0

**Comment by cryptoking233** [comment]
I am not 100% sure about the issues you are having. A few tips I can provide though is for me to get it working I did not use a virtualenv or the latest version of python. I opened the command window in the folder with all the files and had to run python 2.7.10 to connect to websocket. Hope this helps and good luck. I have been running it today and have had decent returns on main after testing it on testnet. I have had a few issues with it crashing during rallies or at random times.

**Comment by ec-mr-anderson** [comment]
Thanks.  Your information does give me some ideas.  I am not using virtualenv either.  It might be a Python 3's import issue.  As I get the same error when just trying to import that module from Python CLI.  I am going to try a few thing and maybe just make it work with Python 2.7.

>>> from market_maker.settings import settings
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/oracle/git/sample-market-maker/market_maker/settings.py", line 22, in <module>
    userSettings = import_path(os.path.join('..', 'settings'))
  File "/home/oracle/git/sample-market-maker/market_maker/settings.py", line 17, in import_path
    module = __import__(filename)
ModuleNotFoundError: No module named 'settings'

**Comment by jji3867** [comment]
Never mind.  I was an idiot.  I didn't run the setup.py to generate a settings.py under the top level directory.  I thought the settings.py under market_maker was the one to use.

I am good now.  Thanks.

**Comment by ec-mr-anderson** [comment]
Never mind.  I was an idiot.  I thought the settings.py under market_maker was the one.  I didn't run setup.py to generate a settings.py under top level dir.

I am good now.
Thanks.
