### ISSUE TITLE
Unable to start using pip install

### ISSUE THREAD

**Issue by dimirey** [BitMEX/sample-market-maker#64]
I've followed the instructions for installation but I am unable to run the program due to this error:

```
➜  bot marketmaker XBTUSD
Traceback (most recent call last):
  File "/Users/dimitri/.pyenv/versions/3.5.0/bin/marketmaker", line 9, in <module>
    load_entry_point('bitmex-market-maker==1.3', 'console_scripts', 'marketmaker')()
  File "/Users/dimitri/.pyenv/versions/3.5.0/lib/python3.5/site-packages/market_maker/__init__.py", line 21, in run
    from market_maker import market_maker
  File "/Users/dimitri/.pyenv/versions/3.5.0/lib/python3.5/site-packages/market_maker/market_maker.py", line 11, in <module>
    from market_maker import bitmex
  File "/Users/dimitri/.pyenv/versions/3.5.0/lib/python3.5/site-packages/market_maker/bitmex.py", line 12, in <module>
    from market_maker.ws.ws_thread import BitMEXWebsocket
  File "/Users/dimitri/.pyenv/versions/3.5.0/lib/python3.5/site-packages/market_maker/ws/ws_thread.py", line 10, in <module>
    from market_maker.settings import settings
  File "/Users/dimitri/.pyenv/versions/3.5.0/lib/python3.5/site-packages/market_maker/settings.py", line 25, in <module>
    userSettings = import_path(os.path.join('.', 'settings'))
  File "/Users/dimitri/.pyenv/versions/3.5.0/lib/python3.5/site-packages/market_maker/settings.py", line 19, in import_path
    module = importlib.import_module(filename, path)
  File "/Users/dimitri/.pyenv/versions/3.5.0/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 981, in _gcd_import
  File "<frozen importlib._bootstrap>", line 931, in _sanity_check
SystemError: Parent module '.' not loaded, cannot perform relative import
```

**Comment by ryanfox** [comment]
1. How did you install the library?
2. How are you starting the application?

**Comment by dimirey** [comment]
I installed globally via pip: pip install bitmex-market-maker

I configured the settings file as per instructions and tried running` marketmaker XBTUSD` within the created folder

**Comment by ryanfox** [comment]
Try running it from the same directory you ran `marketmaker setup` in.

**Comment by dimirey** [comment]
Doesn't work, getting this error:

`marketmaker "XBTUSD"
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/bin/marketmaker", line 9, in <module>
    load_entry_point('bitmex-market-maker==1.3', 'console_scripts', 'marketmaker')()
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/bitmex_market_maker-1.3-py3.5.egg/market_maker/__init__.py", line 21, in run
    from market_maker import market_maker
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/bitmex_market_maker-1.3-py3.5.egg/market_maker/market_maker.py", line 11, in <module>
    from market_maker import bitmex
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/bitmex_market_maker-1.3-py3.5.egg/market_maker/bitmex.py", line 12, in <module>
    from market_maker.ws.ws_thread import BitMEXWebsocket
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/bitmex_market_maker-1.3-py3.5.egg/market_maker/ws/ws_thread.py", line 10, in <module>
    from market_maker.settings import settings
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/bitmex_market_maker-1.3-py3.5.egg/market_maker/settings.py", line 25, in <module>
    userSettings = import_path(os.path.join('.', 'settings'))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/bitmex_market_maker-1.3-py3.5.egg/market_maker/settings.py", line 19, in import_path
    module = importlib.import_module(filename, path)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 981, in _gcd_import
  File "<frozen importlib._bootstrap>", line 931, in _sanity_check
SystemError: Parent module '.' not loaded, cannot perform relative import`

**Comment by SirHodlington** [comment]
I'm having the same issue on windows and on linux servers

**Comment by SirHodlington** [comment]
[ec2-user@ip-xxx-xx-xx-xxx ~]$ marketmaker XBTUSD
Traceback (most recent call last):
  File "/usr/local/bin/marketmaker", line 11, in <module>
    load_entry_point('bitmex-market-maker==1.3', 'console_scripts', 'marketmaker')()
  File "/usr/local/lib/python2.7/site-packages/market_maker/__init__.py", line 21, in run
    from market_maker import market_maker
  File "/usr/local/lib/python2.7/site-packages/market_maker/market_maker.py", line 11, in <module>
    from market_maker import bitmex
  File "/usr/local/lib/python2.7/site-packages/market_maker/bitmex.py", line 12, in <module>
    from market_maker.ws.ws_thread import BitMEXWebsocket
  File "/usr/local/lib/python2.7/site-packages/market_maker/ws/ws_thread.py", line 10, in <module>
    from market_maker.settings import settings
  File "/usr/local/lib/python2.7/site-packages/market_maker/settings.py", line 25, in <module>
    userSettings = import_path(os.path.join('.', 'settings'))
  File "/usr/local/lib/python2.7/site-packages/market_maker/settings.py", line 20, in import_path
    importlib.reload(module)  # Might be out of date
AttributeError: 'module' object has no attribute 'reload'

**Comment by ryanfox** [comment]
@SirHodlington Python 2 is not supported.

@dimirey How did you install the package? `/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/bitmex_market_maker-1.3-py3.5.egg/market_maker/__init__.py` looks wrong.

**Comment by dimirey** [comment]
@ryanfox I installed using `pip install bitmex-market-maker`

**Comment by ryanfox** [comment]
It doesn't look like your script is using the version you pip installed, the pypi release doesn't have an egg. What results do you get if you run

    which python

and launch a python console and run

    >>> import marketmaker
    >>> marketmaker

**Comment by dimirey** [comment]
```
➜  ~ which python
python: aliased to python3

➜  ~ python
Python 3.5.0 (v3.5.0:374f501f4567, Sep 12 2015, 11:00:19)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import marketmaker
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'marketmaker'
>>> marketmaker
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'marketmaker' is not defined
>>>
```

**Comment by ryanfox** [comment]
The `python` you are running doesn't have marketmaker installed. You might try uninstalling, and reinstalling. I'm not sure that will work though, that `.egg` file is strange, pip should not have installed that.

It's a good idea to use a virtualenv in general - it makes it easy to ensure you are getting a clean install.

**Comment by fabrixpo** [comment]
I'm experiencing the same issue. Tried to uninstall and reinstall the market-maker script but no success. 
I used a virtualenv but maybe a detailed step-by-step description could help.

**Comment by ryanfox** [comment]
The README has step by step instructions: https://github.com/BitMEX/sample-market-maker#getting-started

**Comment by fabrixpo** [comment]
followed exactly these instructions but these seems to miss some important thing
