### ISSUE TITLE
marketmaker setup is not working

### ISSUE THREAD

**Issue by tingko10** [BitMEX/sample-market-maker#67]
~/sample-market-maker$ ./marketmaker setup
Traceback (most recent call last):
  File "./marketmaker", line 3, in <module>
    from market_maker import market_maker
  File "/home/ttt/sample-market-maker/market_maker/market_maker.py", line 11, in <module>
    from market_maker import bitmex
  File "/home/ttt/sample-market-maker/market_maker/bitmex.py", line 12, in <module>
    from market_maker.ws.ws_thread import BitMEXWebsocket
  File "/home/ttt/sample-market-maker/market_maker/ws/ws_thread.py", line 10, in <module>
    from market_maker.settings import settings
  File "/home/ttt/sample-market-maker/market_maker/settings.py", line 25, in <module>
    userSettings = import_path(os.path.join('.', 'settings'))
  File "/home/ttt/sample-market-maker/market_maker/settings.py", line 19, in import_path
    module = importlib.import_module(filename, path)
  File "/home/ttt/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'settings'
---------------------------------------------------------------------------

anyone can help me?

**Comment by ryanfox** [comment]
You need to run the command `marketmaker`, not the local file `./marketmaker`.

Additionally, you should only have the project repo locally if you are developing for the library. Otherwise, installing via `pip install bitmex-market-maker` is recommended.

**Comment by 0xJchen** [comment]
> You need to run the command `marketmaker`, not the local file `./marketmaker`.
> 
> Additionally, you should only have the project repo locally if you are developing for the library. Otherwise, installing via `pip install bitmex-market-maker` is recommended.

on `ubuntu 22.04` with `python3.8.10`, directly calling gives `marketmaker: command not found` error.
