### ISSUE TITLE
can not run marketmaker

### ISSUE THREAD

**Issue by gant2018** [BitMEX/sample-market-maker#73]
when i start marketmaker XBTUSD i have following error. What to do ?

using python 2.7.10 and virtualenv

erik$marketmaker XBTUSD
Traceback (most recent call last):
  File "/Users/erik/Documents/testmm/testmam/bin/marketmaker", line 11, in <module>
    sys.exit(run())
  File "/Users/erik/Documents/testmm/testmam/lib/python2.7/site-packages/market_maker/__init__.py", line 21, in run
    from market_maker import market_maker
  File "/Users/erik/Documents/testmm/testmam/lib/python2.7/site-packages/market_maker/market_maker.py", line 11, in <module>
    from market_maker import bitmex
  File "/Users/erik/Documents/testmm/testmam/lib/python2.7/site-packages/market_maker/bitmex.py", line 12, in <module>
    from market_maker.ws.ws_thread import BitMEXWebsocket
  File "/Users/erik/Documents/testmm/testmam/lib/python2.7/site-packages/market_maker/ws/ws_thread.py", line 10, in <module>
    from market_maker.settings import settings
  File "/Users/erik/Documents/testmm/testmam/lib/python2.7/site-packages/market_maker/settings.py", line 25, in <module>
    userSettings = import_path(os.path.join('.', 'settings'))
  File "/Users/erik/Documents/testmm/testmam/lib/python2.7/site-packages/market_maker/settings.py", line 20, in import_path
    importlib.reload(module)  # Might be out of date
AttributeError: 'module' object has no attribute 'reload'

**Comment by Asteezy24** [comment]
I also have this issue.

**Comment by ryanfox** [comment]
Python 2 is not supported. Use Python 3.5 or newer.

**Comment by HeshamMahrous** [comment]
who wants to use python 3.5 if you want to run a proper AI bot !

**Comment by webdev23** [comment]
Whoever took the idea to make python not backward compatible, just fucked up the INTERNET.

**Comment by meph1st0pheles** [comment]
Hi, I'm getting the same issue but when I check the python version is says it's running in 3.

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/marketmaker", line 11, in <module>
    sys.exit(run())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/market_maker/__init__.py", line 21, in run
    from market_maker import market_maker
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/market_maker/market_maker.py", line 11, in <module>
    from market_maker import bitmex
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/market_maker/bitmex.py", line 12, in <module>
    from market_maker.ws.ws_thread import BitMEXWebsocket
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/market_maker/ws/ws_thread.py", line 10, in <module>
    from market_maker.settings import settings
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/market_maker/settings.py", line 25, in <module>
    userSettings = import_path(os.path.join('.', 'settings'))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/market_maker/settings.py", line 20, in import_path
    importlib.reload(module)  # Might be out of date

Do I need to change the path of the settings.py?
