### ISSUE TITLE
 global name 'FileExistsError' is not defined

### ISSUE THREAD

**Issue by AshishBaboo** [BitMEX/sample-market-maker#90]
I am working on windows 10.
installed bitmex market maker succesfully. Running marketmaker setup but giving below error.

PS C:\Users\ashish.baboo\Desktop\sample-market-maker-master> marketmaker setup
Traceback (most recent call last):
  File "C:\Python27\Scripts\marketmaker-script.py", line 11, in <module>
    load_entry_point('bitmex-market-maker==1.3', 'console_scripts', 'marketmaker')()
  File "c:\python27\lib\site-packages\market_maker\__init__.py", line 16, in run
    copy_files()
  File "c:\python27\lib\site-packages\market_maker\__init__.py", line 36, in copy_files
    except FileExistsError:
NameError: global name 'FileExistsError' is not defined

**Comment by ryanfox** [comment]
Python 3 is required to use the library. `FileExistsError` was added to python in 3.3.

**Comment by AshishBaboo** [comment]
Hi Ryan, Thank you for the help. However now i am getting new error. Which is  as below.

Importing symbol settings for XBTUSD...
Unable to find settings-XBTUSD.py.
2018-04-05 21:42:15,280 - INFO - market_maker - BitMEX Market Maker Version: 1.0

2018-04-05 21:42:15,282 - INFO - ws_thread - Connecting to wss://testnet.bitmex.com/realtime?subscribe=quote:XBTUSD,trade:XBTUSD,orderBook25:XBTUSD,instrument,order:XBTUSD,execution:XBTUSD,margin,position
2018-04-05 21:42:15,282 - INFO - ws_thread - Authenticating with API Key.
2018-04-05 21:42:15,282 - INFO - ws_thread - Started thread
2018-04-05 21:42:17,414 - ERROR - ws_thread - Unknown table: orderBook25
No handlers could be found for logger "websocket"
2018-04-05 21:42:18,315 - ERROR - ws_thread - Couldn't connect to WS! Exiting.

**Comment by ryanfox** [comment]
The only `orderBook25` in the repository is commented out - errors encountered after modifying the code are out of scope for this issue tracker. Consider this caveat from the README:
> This code is intended for sample purposes ONLY - do not use this code for real trades unless you fully understand what it does and what its caveats are.

If you encounter issues with the library code, open a ticket as appropriate.
