### ISSUE TITLE
Exceptions in multiple lines and files

### ISSUE THREAD

**Issue by AlexADittrich** [BitMEX/sample-market-maker#98]
Upon starting, I keep receiving the following exceptions. Is this expected?

`Traceback (most recent call last):
  File "c:\program files (x86)\python36-32\lib\site-packages\urllib3\connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "c:\program files (x86)\python36-32\lib\site-packages\urllib3\connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "c:\program files (x86)\python36-32\lib\http\client.py", line 1331, in getresponse
    response.begin()
  File "c:\program files (x86)\python36-32\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "c:\program files (x86)\python36-32\lib\http\client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "c:\program files (x86)\python36-32\lib\socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "c:\program files (x86)\python36-32\lib\ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "c:\program files (x86)\python36-32\lib\ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "c:\program files (x86)\python36-32\lib\ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files (x86)\python36-32\lib\site-packages\requests\adapters.py", line 440, in send
    timeout=timeout
  File "c:\program files (x86)\python36-32\lib\site-packages\urllib3\connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "c:\program files (x86)\python36-32\lib\site-packages\urllib3\util\retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "c:\program files (x86)\python36-32\lib\site-packages\urllib3\packages\six.py", line 686, in reraise
    raise value
  File "c:\program files (x86)\python36-32\lib\site-packages\urllib3\connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "c:\program files (x86)\python36-32\lib\site-packages\urllib3\connectionpool.py", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "c:\program files (x86)\python36-32\lib\site-packages\urllib3\connectionpool.py", line 309, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='www.bitmex.com', port=443): Read timed out. (read timeout
=2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files (x86)\python36-32\lib\site-packages\market_maker\bitmex.py", line 261, in _curl_bitmex
    response = self.session.send(prepped, timeout=timeout)
  File "c:\program files (x86)\python36-32\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "c:\program files (x86)\python36-32\lib\site-packages\requests\adapters.py", line 521, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='www.bitmex.com', port=443): Read timed out. (read timeout=2)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files (x86)\Python36-32\Scripts\marketmaker-script.py", line 11, in <module>
    load_entry_point('bitmex-market-maker==1.3', 'console_scripts', 'marketmaker')()
  File "c:\program files (x86)\python36-32\lib\site-packages\market_maker\__init__.py", line 22, in run
    market_maker.run()
  File "c:\program files (x86)\python36-32\lib\site-packages\market_maker\market_maker.py", line 550, in run
    om.init()
  File "c:\program files (x86)\python36-32\lib\site-packages\market_maker\market_maker.py", line 221, in init
    self.reset()
  File "c:\program files (x86)\python36-32\lib\site-packages\market_maker\market_maker.py", line 224, in reset
    self.exchange.cancel_all_orders()
  File "c:\program files (x86)\python36-32\lib\site-packages\market_maker\market_maker.py", line 66, in cancel_all_order
s
    self.bitmex.cancel([order['orderID'] for order in orders])
  File "c:\program files (x86)\python36-32\lib\site-packages\market_maker\bitmex.py", line 104, in wrapped
    return fn(self, *args, **kwargs)
  File "c:\program files (x86)\python36-32\lib\site-packages\market_maker\bitmex.py", line 207, in cancel
    return self._curl_bitmex(path=path, postdict=postdict, verb="DELETE")
  File "c:\program files (x86)\python36-32\lib\site-packages\market_maker\bitmex.py", line 351, in _curl_bitmex
    return retry()
  File "c:\program files (x86)\python36-32\lib\site-packages\market_maker\bitmex.py", line 253, in retry
    return self._curl_bitmex(path, query, postdict, timeout, verb, rethrow_errors, max_retries)
  File "c:\program files (x86)\python36-32\lib\site-packages\market_maker\bitmex.py", line 351, in _curl_bitmex
    return retry()
  File "c:\program files (x86)\python36-32\lib\site-packages\market_maker\bitmex.py", line 253, in retry
    return self._curl_bitmex(path, query, postdict, timeout, verb, rethrow_errors, max_retries)
  File "c:\program files (x86)\python36-32\lib\site-packages\market_maker\bitmex.py", line 351, in _curl_bitmex
    return retry()
  File "c:\program files (x86)\python36-32\lib\site-packages\market_maker\bitmex.py", line 253, in retry
    return self._curl_bitmex(path, query, postdict, timeout, verb, rethrow_errors, max_retries)
  File "c:\program files (x86)\python36-32\lib\site-packages\market_maker\bitmex.py", line 351, in _curl_bitmex
    return retry()
  File "c:\program files (x86)\python36-32\lib\site-packages\market_maker\bitmex.py", line 252, in retry
    raise Exception("Max retries on %s (%s) hit, raising." % (path, json.dumps(postdict or '')))`

**Comment by ryanfox** [comment]
How is your environment set up? How are you running the application?

That is a timeout error - does it happen every time, or sporadically? Is it possible you have a firewall blocking the connection?

**Comment by AlexADittrich** [comment]
This is running on python 3.6.5. Installed with pip.

I invoke marketmaker from powershell.

This seems to only happen sporadically, and in alignment with API overload/outages from the bitmex endpoint. I do not believe a firewall is the source of the issue. Thanks a lot for you response.

**Comment by ryanfox** [comment]
A more robust application might catch the error and attempt to reconnect - this is not an advanced application.

Regardless, if you wanted to keep the market maker running, you could try [any method powershell permits to restart an application.](https://stackoverflow.com/questions/46182207/how-to-repeat-a-command-forever-in-powershell)

**Comment by plzure** [comment]
Have the same problem
